### PR TITLE
fix (protocols): support wms in EPSG:3857 projection

### LINKED ISSUE #478: EPSG:3857 (PseudoMercator) projection not handled for WMS layers
## Context
WMS layers can't be added in PseudoMercator (EPSG:3857), but only in WGS84 (EPSG:4326). 

If we change the projection property of a WMS layer object to "EPSG:3857", the following error is launched and the WMS layer isn't displayed :

> non-coherent result 0 0 vs 1. [object Object]

On the other hand, there is no problem with WMTS layers added in EPSG:3857.

## Steps to Reproduce
1. Change the projection property of a WMS layer to "EPSG:3857" (itowns/examples/layers/JSONLayers/Region.json for instance)
2. Add it to the globe (see itowns/index.html)

## Expected Behavior
The region layer is displayed.

## Actual Behavior
The region layer is not display and error is launched in the dev console.

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description
wms protocol supports  in `EPSG:3857` projection

## Motivation and Context
wms protocol only supported the `EPSG:4326`
fix #478

### CODE REVIEW

File: src/Core/Scheduler/Providers/WMS_Provider.js [hunk 1]
```diff
@@ -134,4 +152,18 @@ WMS_Provider.prototype.executeCommand = function executeCommand(command) {
...
 };
 
+WMS_Provider.prototype.getColorTextures = function getColorTextures(tile, layer, targetLevel) {
+    if (tile.material === null) {
+        return Promise.resolve();
+    }
+    const promises = [];
+    const bcoord = tile.getCoordsForLayer(layer);
+
+    for (const coordWMTS of bcoord) {
```
Comment (peppsac) [inline src/Core/Scheduler/Providers/WMS_Provider.js]: Why a WMS provider would want to return several image for a single tile?

File: src/Core/Scheduler/Providers/WMS_Provider.js [hunk 2]
```diff
@@ -69,13 +82,21 @@ WMS_Provider.prototype.preprocessDataLayer = function preprocessDataLayer(layer)
...
+        }
+        if (c.zoom < layer.options.zoom.min || c.zoom > layer.options.zoom.max) {
+            return false;
+        }
+    }
+    return true;
 };
 
-WMS_Provider.prototype.getColorTexture = function getColorTexture(tile, layer, targetLevel) {
+WMS_Provider.prototype.getColorTexture = function getColorTexture(coordWMTS, layer, tile, targetLevel) {
```
Comment (peppsac) [inline src/Core/Scheduler/Providers/WMS_Provider.js]: `coordWMTS` name seems out of place in a WMTS_Provider. Can you explain why you use this name?

File: src/Core/Scheduler/Providers/WMS_Provider.js [hunk 3]
```diff
@@ -97,20 +115,20 @@ WMS_Provider.prototype.getColorTexture = function getColorTexture(tile, layer, t
         }
         extent = parentAtLevel.extent;
         targetLevel = parentAtLevel.level;
+        const pow = 1 / (coordWMTS.zoom - targetLevel);
+        const row = Math.floor(Math.pow(coordWMTS.row, pow));
```
Comment (peppsac) [inline src/Core/Scheduler/Providers/WMS_Provider.js]: `row` and `column` stuff seems out of place as well.
Any comments to explain what is going on here?

File: src/Core/Scheduler/Providers/WMS_Provider.js [hunk 4]
```diff
@@ -57,6 +63,13 @@ WMS_Provider.prototype.preprocessDataLayer = function preprocessDataLayer(layer)
     layer.style = layer.style || '';
     layer.transparent = layer.transparent || false;
 
+    if (layer.projection == 'EPSG:3857') {
+        layer.options.tileMatrixSet = 'PM';
```
Comment (peppsac) [inline src/Core/Scheduler/Providers/WMS_Provider.js]: From an outsider look this looks wrong: why WMS would need knowledge of tileMatrixSet?

File: src/Core/Geographic/Extent.js [hunk 5]
```diff
@@ -90,7 +92,37 @@ Extent.prototype.as = function as(crs) {
...
+            const east = 180 - size * (nbCol - (this.col + 1));
+            const nbRow = nbCol;
+            const sizeRow = 1.0 / nbRow;
+            const Yn = 1 - sizeRow * (nbRow - (this.row));
+            const Ys = 1 - sizeRow * (nbRow - (this.row + 1));
+            const north = THREE.Math.radToDeg(projection.YToWGS84(Yn));
+            const south = THREE.Math.radToDeg(projection.YToWGS84(Ys));
+            const minCoord = new Coordinates('EPSG:4326', west, south).as(crs);
+            const maxCoord = new Coordinates('EPSG:4326', east, north).as(crs);
+            return new Extent(crs, {
```
Comment (peppsac) [inline src/Core/Geographic/Extent.js]: Maybe add a comment explaining what you're doing because it's not obvious.

Comment (peppsac) [reply src/Core/Geographic/Extent.js]: Also it seems weird to reference 4326 here and have a completely different computation 5 lines below for 4326?

**Review by peppsac — COMMENTED** [review]
I trust you that it's correct, but comments would help a lot.

Also, while working on 3857 it would be nice to fix `split.html` example...

File: src/Core/Geographic/Extent.js (hunk 5 above)
Comment (gchoqueux) [reply src/Core/Geographic/Extent.js]: i add comment
and fix error state crs

File: src/Core/Scheduler/Providers/WMS_Provider.js (hunk 4 above)
Comment (gchoqueux) [reply src/Core/Scheduler/Providers/WMS_Provider.js]: Previously the `tileMatrixSet` was implicit because the projections were identical. Now, it's necessary to specify in which `tileMatrixSet` the textures are placed

File: src/Core/Scheduler/Providers/WMS_Provider.js (hunk 3 above)
Comment (gchoqueux) [reply src/Core/Scheduler/Providers/WMS_Provider.js]: i rool back on that

File: src/Core/Scheduler/Providers/WMS_Provider.js (hunk 1 above)
Comment (gchoqueux) [reply src/Core/Scheduler/Providers/WMS_Provider.js]: it's same reason that PM tileMatrixSet

**Comment by gchoqueux** [comment]
@peppsac  updated

**Comment by gchoqueux** [comment]
> Also, while working on 3857 it would be nice to fix split.html example

It's access to image problem : `the access has been blocked by CORS policy`

**Comment by peppsac** [comment]
> It's access to image problem : the access has been blocked by CORS policy

Hmm wmtsc pseudo protocol is in transient state. It's not tested in WMTS_Provider preprocess 
layer  but it's still declared as supported in Scheduler... But ok, we'll see this point later.

File: src/Core/Geographic/Extent.js [hunk 6]
```diff
@@ -90,7 +92,34 @@ Extent.prototype.as = function as(crs) {
     assertCrsIsValid(crs);
 
     if (_isTiledCRS(this._crs)) {
-        throw new Error('Unsupported yet');
+        if (this._crs == 'WMTS:PM') {
```
Comment (peppsac) [inline src/Core/Geographic/Extent.js:95]: Can you add something describing the intent here - which seems to be: convert `this` to the requested crs by using `4326` as an intermediate state.

File: src/Core/Scheduler/Providers/WMS_Provider.js [hunk 7]
```diff
@@ -57,6 +67,16 @@ WMS_Provider.prototype.preprocessDataLayer = function preprocessDataLayer(layer)
     layer.style = layer.style || '';
     layer.transparent = layer.transparent || false;
 
+    // add tileMatrixSet destination to tile
```
Comment (peppsac) [inline src/Core/Scheduler/Providers/WMS_Provider.js]: I still think that this doesn't belong to WMS_Provider.

Let me know if I understand correctly: the info you're adding here are helping to convert extent from the geometry to extent(s) in the layer's crs?

In which case maybe it would make sense to move this to `TileMesh.getCoordsForLayer`... WDYT?

**Comment by gchoqueux** [comment]
@peppsac @elias75015 updated
add new : fix error conversion latitude 4326 to 3857

**Review by peppsac — COMMENTED** [review]
Looks ok now. Can you rebase before merging please?

**Comment by gchoqueux** [comment]
@peppsac rebased

**Review by peppsac — APPROVED** [review]
