### PR TITLE
Mapbox style multiple source

### LINKED ISSUE #1927: Mapbox Style with multiple sources not being rendered correctly
Hi,
    I'm trying to use a Mapbox vector style that is working fine for a 2D map using Openalyers + ol-maplibre-layer.
    Using the same json file as style leads to only 1 layer being shown.

## Your Environment

* Version used: 2.38.2
* Browser Name and version: chrome 106.0.5249.119
* Operating System and version (desktop or mobile): Linux Desktop
* Link to your project: 

## Context

  The style json file has multiple sources as below :-
```
  "sources": {
    "physical": {
      "type": "vector",
      "tiles": [
        "http://localhost:8000/services/physical/tiles/{z}/{x}/{y}.pbf"
      ],
      "minZoom": 2,
      "maxZoom": 14
    },
    "land": {
      "type": "vector",
      "tiles": [
        "http://localhost:8000/services/land/tiles/{z}/{x}/{y}.pbf"
      ],
      "minZoom": 2,
      "maxZoom": 14
    }
  }
  "layers":[
    { 
      {
      "id": "marine",
      "type": "fill",
      "source": "physical",
      "source-layer": "marine",
     },
   },
   {
      "id": "land",
      "type": "fill",
      "source": "land",
      "source-layer": "land",
      "paint": {
        "fill-color": "#ccffff",
        "fill-antialias": true
      }
    },
 ]
```

## Steps to Reproduce (for bugs)

1.  Use a mapbox style with multiple sources 

## Expected Behavior

All the layers referencing all the sources should be displayed.

## Actual Behavior

Only the first layer referencing the first source is displayed

All the layers referencing all the sources should be displayed.

### PR DESCRIPTION
**Pull request by a-dutremble**
## Description
Add multiple source Mapbox style support.
We've modified the entire process: source, url builder, fetcher and parser.

## Motivation and Context
Fixes #1927 

## Follow up after the departure of Aymeric
I took this review into my hand and did the changes I found neccessary and improvment I think was needed. I choose not to delete the commit from aymeric to be able to see what he did before my changes. At the end before the merging, the commits will be squashed.

### CODE REVIEW

File: src/Provider/URLBuilder.js [hunk 1]
```diff
@@ -63,9 +63,19 @@ export default {
...
      */
     xyz: function xyz(coords, source) {
-        return subDomains(source.url.replace(/(\$\{z\}|%TILEMATRIX)/, source.tileMatrixCallback(coords.zoom))
-            .replace(/(\$\{y\}|%ROW)/, coords.row)
-            .replace(/(\$\{x\}|%COL)/, coords.col));
+        if (typeof source.url === 'string') {
+            return subDomains(source.url.replace(/(\$\{z\}|%TILEMATRIX)/, source.tileMatrixCallback(coords.zoom))
+                .replace(/(\$\{y\}|%ROW)/, coords.row)
+                .replace(/(\$\{x\}|%COL)/, coords.col));
+        } else if (Array.isArray(source.url)) {
```
Comment (ftoromanoff) [inline src/Provider/URLBuilder.js]: instead of dealing with the multi url inside this function it should be done earlier and, this function should be called x times (x being the length of the array)

File: src/Parser/VectorTileParser.js [hunk 2]
```diff
@@ -209,6 +224,10 @@ export default {
      */
     parse(file, options) {
         options = deprecatedParsingOptionsToNewOne(options);
-        return Promise.resolve(readPBF(file, options));
+        if (Array.isArray(file)) {
+            return Promise.resolve(multiplePBF(file, options));
+        } else {
+            return Promise.resolve(readPBF(file, options));
+        }
```
Comment (ftoromanoff) [inline src/Parser/VectorTileParser.js]: If we think about the name and utility of this function, it is writen to parse a specifique file and thus it shouldn't be able to deal with a list of files.

File: src/Provider/Fetcher.js [hunk 3]
```diff
@@ -15,6 +15,25 @@ const arrayBuffer = (url, options = {}) => fetch(url, options).then((response) =
     return response.arrayBuffer();
 });
 
+const mapbox = (url, options = {}) => {
```
Comment (ftoromanoff) [inline src/Provider/Fetcher.js]: This fethchershould be more generic, as 'mutlisource' and then know it needs to call the arraybuffer fetcher several time. (or an other one if needed.

Maybe it should be the fetcher arrayBuffer (and other) that are able to deal with multisource.

File: src/Source/Source.js [hunk 4]
```diff
@@ -16,7 +16,7 @@ export const supportedFetchers = new Map([
     ['application/json', Fetcher.json],
     ['application/kml', Fetcher.xml],
     ['application/gpx', Fetcher.xml],
-    ['application/x-protobuf;type=mapbox-vector', Fetcher.arrayBuffer],
+    ['application/x-protobuf;type=mapbox-vector', Fetcher.mapbox],
```
Comment (ftoromanoff) [inline src/Source/Source.js]: same
Fetcher.multisource that can recognize arrayBuffer
OR
Fetcher.arrayBuffer that can deal with multisource  ?

File: src/Source/Source.js [hunk 5]
```diff
@@ -70,8 +70,15 @@ function fetchSourceData(source, extent) {
     const url = source.urlFromExtent(extent);
 
     return source.fetcher(url, source.networkOptions).then((f) => {
-        f.extent = extent;
-        return f;
+        if (Array.isArray(f)) {
```
Comment (ftoromanoff) [inline src/Source/Source.js]: should be done earlier

**Review by ftoromanoff — CHANGES_REQUESTED** [review]

File: src/Provider/Fetcher.js [hunk 6]
```diff
@@ -132,6 +132,7 @@ export default {
      * @param {Object} options - Fetch options (passed directly to `fetch()`),
      * see [the syntax for more information]{@link
      * https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch#Syntax}.
+     * @param {Extent} extent
```
Comment (ftoromanoff) [inline src/Provider/Fetcher.js]: To delete

File: test/unit/vectortiles.js [hunk 7]
```diff
@@ -66,159 +67,239 @@ describe('Vector tiles', function () {
...
+    //     source.whenReady
+    //         .then(() => {
+    //             assert.equal(source.url.size, 2);
+    //             // eslint-disable-next-line no-template-curly-in-string
+    //             assert.ok(source.url.has('http://server.geo/${z}/${x}/${y}.pbf'));
+    //             done();
+    //         })
+    //         .catch(done);
+    // });
+
```
Comment (AnthonyGlt) [inline test/unit/vectortiles.js]: Is it a todo ? Maybe link an issue to it

Comment (ftoromanoff) [reply test/unit/vectortiles.js]: I did change the test for it to work, but it will need the Need PR #2183 to be working (to be able to mock the fetcher).
I reworked it but let it in comment for the moment, to avoid the import of the sinon library in this PR.

File: examples/vector_tile_multisource.html [hunk 8]
```diff
@@ -0,0 +1,78 @@
...
+            // Display the content of two GeoJSON files on terrain with ColorLayer and FileSource.
+            // The GeoJSONs are loaded from url, set in FileSource
+
+            // Declare the source for the data on Ariege area
+
+            const buildingsSource = new itowns.VectorTilesSource({
+                style: './layers/JSONLayers/mapbox.json'
+            });
+
+            console.log(buildingsSource);
```
Comment (AnthonyGlt) [inline examples/vector_tile_multisource.html]: log to remove

File: examples/vector_tile_multisource.html [hunk 9]
```diff
@@ -0,0 +1,78 @@
...
+            itowns.Fetcher.json('./layers/JSONLayers/IGN_MNT_HIGHRES.json').then(addElevationLayerFromConfig);
+            itowns.Fetcher.json('./layers/JSONLayers/WORLD_DTM.json').then(addElevationLayerFromConfig);
+
+
+            // Display the content of two GeoJSON files on terrain with ColorLayer and FileSource.
+            // The GeoJSONs are loaded from url, set in FileSource
+
+            // Declare the source for the data on Ariege area
+
+            const buildingsSource = new itowns.VectorTilesSource({
```
Comment (AnthonyGlt) [inline examples/vector_tile_multisource.html]: Rename buildingsSource with multiSources or mapboxSources, WDYT ?

File: examples/vector_tile_multisource.html [hunk 10]
```diff
@@ -0,0 +1,78 @@
...
+                style: './layers/JSONLayers/mapbox.json'
+            });
+
+            console.log(buildingsSource);
+            const mapLayer = new itowns.ColorLayer('test', {
```
Comment (AnthonyGlt) [inline examples/vector_tile_multisource.html]: rename test -> multi-sources-mapbox or something like this ?

**Review by ftoromanoff — DISMISSED** [review]

**Review by AnthonyGlt — APPROVED** [review]
