### PR TITLE
fix(VectorTileSource): failing to open mapbox url format.

### LINKED ISSUE #1551: Mapbox color layer example
Hello everyone,

I'm looking to stylize my map by integrating a link to my mapbox map as a color layer. I saw that the subject has been mentioned here :
https://github.com/iTowns/itowns/issues/182
Then here:
https://github.com/iTowns/itowns/issues/658

But I didn't succeed. So I contact you to know if there is an example with mapbox that I could follow?

Thank you !

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description
iTowns doesn't normalize mapbox url, so It failed to open it.

### CODE REVIEW

File: src/Parser/MapBoxUrlParser.js [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+    }
+    return {
+        protocol: parts[1],
+        authority: parts[2],
+        path: parts[3] || '/',
+        params: parts[4] ? parts[4].split('&') : [],
+    };
+}
+
+function normalizeSpriteURL(url, format, extension, accessToken) {
```
Comment (mgermerie) [inline src/Parser/MapBoxUrlParser.js:58]: For my information, how can sprites be used with itowns ?

**Review by mgermerie — APPROVED** [review]

File: src/Parser/MapBoxUrlParser.js (hunk 1 above)
Comment (gchoqueux) [reply src/Parser/MapBoxUrlParser.js:58]: I add some documentation.
