### PR TITLE
Some labels fixes (see 1473)

### LINKED ISSUE #1473: Main report on Label bugs
Label feature is be introduce recently. It's work in progress to consolidate it.

 :warning: **Don't hesitate to add bugs in this issue if you identify one.**

# This issue lists identified bugs

## 1 | Breaking word without interest

- [x] **Fixed in  #1477**

<p align="center">
  
</p>

**Possible cause** on `Style.js` : **`domElement.style.overflowWrap = 'break-word';`**

## 2 | No horizon culling on label
- [x] **Fixed in  #1477**
<p align="center">
  
</p>

**Brussel** label is visible because the parent tile is visible. we should add a horizon culling on label with little level (see `GlobeLayer.js`)

## 3 | Label flickering
- [x] **Fixed in  #1477**
<p align="center">
  
</p>

Possible fix: Start culling by ordering labels with visibility and level.

## 4 | Bug culling label
- [x] **Fixed in  #1477**
<p align="center">
  
</p>

Possible cause: label is displayed while its parent is not visible.

### PR DESCRIPTION
**Pull request by zarov**
Three commits, to solve three problems listed in #1473 

- **fix(label): breaks word correctly**
It does not break in the middle of it anymore.

- **fix(label): correctly hide dom**
There was a problem for a specific situation. Let's consider that there
is a level 2 node, with four level 3 nodes. The L2 node contains no
DOM elements, while there are some in the L3 nodes. So the DOM in L3
have no parents, they are the first in the hierarchy.  So if we find L2
hidden, we don't go further, and thus inside L3 nodes, and don't hide
the DOM.
This commit fixes this behaviour, by allowing to go further in the
hierarchy until DOM elements are found.

- **fix(label): horizon culling**
Add a proper horizon culling mechanism, by splitting the GlobeLayer
culling to use it.

- **fix(label): reduce flickering by ordering label**
    It is not perfect yet, but the flickering has been reduced by taking into
    account the order the labels have.

- **test(label): add test for `Label2DRenderer`**

### CODE REVIEW

**Comment by zarov** [comment]
I added two commits:
- **test(label): add test for Label2DRenderer**
- **fix(label): reduce jittering by ordering label**
It is not perfect yet, but the jittering has been reduced by taking into
account the order the labels have.

**Comment by gchoqueux** [comment]
>     * **fix(label): reduce jittering by ordering label**
>       It is not perfect yet, but the jittering has been reduced by taking into
>       account the order the labels have.

It reduces **flickering**.

File: src/Core/Label.js [hunk 1]
```diff
@@ -114,10 +120,10 @@ class Label extends THREE.Object3D {
             this.projectedPosition.x = X;
             this.projectedPosition.y = Y;
 
-            this.boundaries.left = x + this.offset.left;
-            this.boundaries.right = x + this.offset.right;
-            this.boundaries.top = y + this.offset.top;
-            this.boundaries.bottom = y + this.offset.bottom;
+            this.boundaries.left = x + this.offset.left - 2;
```
Comment (gchoqueux) [inline src/Core/Label.js:125]: `2` is padding value?

File: src/Core/Label.js [hunk 2]
```diff
@@ -155,9 +161,18 @@ class Label extends THREE.Object3D {
...
         if (elevation && elevation != this.coordinates.z) {
             this.coordinates.z = elevation;
+            if (this.horizonCullingPoint) {
+                this.updateHorizonCullingPoint();
+            }
             return true;
         }
     }
+
+    updateHorizonCullingPoint() {
```
Comment (gchoqueux) [inline src/Core/Label.js:171]: You could use the world position with  `getWorldPosition` instead of `horizonCullingPoint`?

File: src/Renderer/Label2DRenderer.js [hunk 3]
```diff
@@ -21,7 +21,7 @@ class ScreenGrid {
     reset() {
         for (let i = 0; i < this.x; i++) {
             for (let j = 0; j < this.y; j++) {
-                this.grid[i][j] = false;
+                this.grid[i][j].splice(0, this.grid[i][j].length);
```
Comment (gchoqueux) [inline src/Renderer/Label2DRenderer.js:30]: add comment to explain splice.

File: src/Renderer/Label2DRenderer.js [hunk 4]
```diff
@@ -50,16 +56,35 @@ class ScreenGrid {
 
         for (let i = minx; i <= maxx; i++) {
             for (let j = miny; j <= maxy; j++) {
-                if (this.grid[i][j]) {
-                    this.hidden.push(obj);
-                    return false;
+                if (this.grid[i][j].length > 0) {
+                    if (this.grid[i][j].some(l =>
+                        ((obj.boundaries.right > l.boundaries.left && obj.boundaries.right < l.boundaries.right)
```
Comment (gchoqueux) [inline src/Renderer/Label2DRenderer.js]: could you extract `containsBox` and `intersectsBox` methods

File: src/Renderer/Label2DRenderer.js [hunk 5]
```diff
@@ -155,6 +190,8 @@ class Label2DRenderer {
         // visible extent, we can filter more labels.
         } else if (object.zoom.max <= currentMaxZoom || !extent.isPointInside(object.coordinates)) {
             this.grid.hidden.push(object);
+        } else if (object.parent.level < 4 && object.parent.layer.horizonCulling && object.parent.layer.horizonCulling(object.horizonCullingPoint)) {
```
Comment (gchoqueux) [inline src/Renderer/Label2DRenderer.js:184]: could you explain `object.parent.level < 4`?

**Review by gchoqueux — COMMENTED** [review]
Nice Work!!

File: src/Core/Label.js (hunk 1 above)
Comment (zarov) [reply src/Core/Label.js:125]: Yes, I added a comment about it.

File: src/Core/Label.js (hunk 2 above)
Comment (zarov) [reply src/Core/Label.js:171]: Done, thanks for noticing this

File: src/Renderer/Label2DRenderer.js (hunk 3 above)
Comment (zarov) [reply src/Renderer/Label2DRenderer.js:30]: Done

File: src/Renderer/Label2DRenderer.js (hunk 4 above)
Comment (zarov) [reply src/Renderer/Label2DRenderer.js]: Done

File: src/Renderer/Label2DRenderer.js (hunk 5 above)
Comment (zarov) [reply src/Renderer/Label2DRenderer.js:184]: Done

**Review by gchoqueux — APPROVED** [review]
