### PR TITLE
3D tiles: fix a bug and improve perfs

### LINKED ISSUE #2074: BatchID in 3DTiles are float and negative
Some batch id in 3DTiles of:

* http://localhost:8080/examples/#3dtiles_25d
* http://localhost:8080/examples/#3dtiles_ion

are float and even negative which does not match [3DTiles specs](https://github.com/CesiumGS/3d-tiles/tree/main/specification/TileFormats/Batched3DModel)

## Your Environment
Google chrome Version 112.0.5615.49 (Build officiel) (64 bits), Ubuntu

## Steps to Reproduce (for bugs)
Have spot the bug on a fork branch [here](https://github.com/VCityTeam/Itowns/tree/bug-float-batchid). Pull then npm start to the examples I said above.

I have spot this bug in the onTileContentLoaded of the C3DTilesLayer, don't know if this is code before doing this or if this is the 3DTiles used.

### PR DESCRIPTION
**Pull request by jailln**
## Description
This PR introduces two changes:

* Fixes #2074 (that also caused tiles to be removed and never loaded again when removed from the cache): the issue came from accessing threejs buffer attributes array directly instead of using the recommended `getX()` method (which is not the same in the case of [InterleavedBufferAttribute](https://threejs.org/docs/index.html?q=interleaved#api/en/core/InterleavedBufferAttribute).

* Greatly improves 3D tiles perfs (see screenshots below) by reducing loading time overhead due to internal structures pre-filling (mainly for 3D tiles picking and style) -> part of these structures are now filled on first demand.

## Screenshots

Performance profiling on `3dtiles_ion.html` example before the second commit:

before-PR-getInfoById

Performance profiling on `3dtiles_ion.html` example after the second commit:

afterPR-getInfoById

### CODE REVIEW

File: src/Core/3DTiles/utils/3DTilesUtils.js [hunk 1]
```diff
@@ -0,0 +1,21 @@
+/**
+ * Finds the batch table of an object in a 3D Tiles layer. This is
+ * for instance needed when picking because we pick the geometric
+ * object which is not at the same level in the layer structure as
+ * the batch table. More details here on itowns internal
+ * organization of 3DTiles:
+ *  https://github.com/MEPP-team/RICT/blob/master/Doc/iTowns/Doc.md#itowns-internal-organisation-of-3d-tiles-data
+ * @param {THREE.Object3D} object - a 3D geometric object
+ * @returns {C3DTBatchTable} - the batch table of the object
```
Comment (Desplandis) [inline src/Core/3DTiles/utils/3DTilesUtils.js]:
```suggestion
 * @returns {C3DTBatchTable|null} - the batch table of the object
```

File: src/Core/3DTiles/C3DTFeature.js [hunk 2]
```diff
@@ -1,5 +1,6 @@
 // eslint-disable-next-line no-unused-vars
 import { Object3D, Box3 } from 'three';
+import findBatchTable from './utils/3DTilesUtils';
```
Comment (Desplandis) [inline src/Core/3DTiles/C3DTFeature.js]: `findBatchTable` was moved from `C3DTilesLayer` to its own file. However, it is only used once and not exported to the end-user. Shall we move it here instead?

File: src/Core/3DTiles/C3DTFeature.js [hunk 3]
```diff
@@ -37,11 +36,12 @@ class C3DTFeature {
         /** @type {object} */
         this.userData = userData;
 
-        /** @type {object} */
-        this.#info = info;
-
         /** @type {number} */
         this.tileId = tileId;
+
+        // Holds the information from the batch table for this.batchId. Will be filled the first time this information
```
Comment (Desplandis) [inline src/Core/3DTiles/C3DTFeature.js]: I usually use the term "lazy-loaded" x)

File: src/Core/3DTiles/C3DTFeature.js [hunk 4]
```diff
@@ -8,19 +9,17 @@ import { Object3D, Box3 } from 'three';
...
  * @property {Object3D} object3d - object3d in which feature is present
  * @property {number} batchId - batch id
  * @property {Array<{start:number,count:number}>} groups - groups in geometry.attributes matching batchId
- * @property {object} info - info in the batchTable
  * @property {object} [userData] - some userData
  */
 class C3DTFeature {
     #info;
-    constructor(tileId, batchId, groups, info, userData, object3d) {
+    constructor(tileId, batchId, groups, userData, object3d) {
```
Comment (Desplandis) [inline src/Core/3DTiles/C3DTFeature.js:39]: This is some breaking change since `C3DTFeature` is exposed to the end-user.
However, is there anyone which instantiates `C3DTFeature` directly? Why it is exposed then?

File: src/Layer/C3DTilesLayer.js [hunk 5]
```diff
@@ -225,25 +225,6 @@ class C3DTilesLayer extends GeometryLayer {
...
-     * Finds the batch table of an object in a 3D Tiles layer. This is
-     * for instance needed when picking because we pick the geometric
-     * object which is not at the same level in the layer structure as
-     * the batch table. More details here on itowns internal
-     * organization of 3DTiles:
-     *  https://github.com/MEPP-team/RICT/blob/master/Doc/iTowns/Doc.md#itowns-internal-organisation-of-3d-tiles-data
-     * @param {THREE.Object3D} object - a 3D geometric object
-     * @returns {C3DTBatchTable} - the batch table of the object
-     */
-    findBatchTable(object) {
```
Comment (Desplandis) [inline src/Layer/C3DTilesLayer.js:238]: Reason to not expose this method anymore (i.e. remove it)?

File: src/Layer/C3DTilesLayer.js [hunk 6]
```diff
@@ -328,17 +304,18 @@ class C3DTilesLayer extends GeometryLayer {
...
                     }
                 };
 
-                for (let index = 0; index < geometryAttributes.position.array.length; index += geometryAttributes.position.itemSize) {
-                    const batchIndex = index / geometryAttributes.position.itemSize;
-                    const batchId = geometryAttributes._BATCHID.array[batchIndex];
+                const positionAttribute = child.geometry.getAttribute('position');
+                const positionAttributeSize = positionAttribute.count * positionAttribute.itemSize;
+                for (let index = 0; index < positionAttributeSize; index += positionAttribute.itemSize) {
+                    const batchIndex = index / positionAttribute.itemSize;
```
Comment (Desplandis) [inline src/Layer/C3DTilesLayer.js:319]: Why are you incrementing by `posititonAttribute.itemSize` only to divide the `index` by `positionAttribute.item` in the following line?

Could you not increment it by 1 and stop the iteration at `positionAttributeSize.count`?

**Review by Desplandis — CHANGES_REQUESTED** [review]
Nice PR! I added some comments about a few odd things but they are minor. =)

Nice perf gain BTW.

File: src/Core/3DTiles/C3DTFeature.js (hunk 4 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTFeature.js:39]: Yes it is but I had the same interrogations and I think the answers are nobody instantiates it directly and it shouldn't be exposed (I looked into LIRIS's code which are the main users of this and haven't seen any instantiation of `C3DTFeature`). We should remove it from the public API but I guess this is the purpose of another PR. Meanwhile I think we should accept having this breaking change and document it in the commit (and therefore the release), but no strong opinions on this, we can also do it differently. WDYT ?

File: src/Layer/C3DTilesLayer.js (hunk 5 above)
Comment (jailln) [reply src/Layer/C3DTilesLayer.js:238]: Mmmh I went a bit too fast I think :grin: However I think it should not have been exposed in the first place (no real use outside of itowns). I can either:
* leave it like this and add a BREAKING CHANGE message
* reintroduce `3DTilesUtils` (with `findBatchTable` in it) and export it (still breaking change but with a fallback elsewhere in the API)
* add it back here and make it call `3DTilesUtils.findBatchTable()`

I'd rather do the first one, but WDYT?

File: src/Layer/C3DTilesLayer.js (hunk 6 above)
Comment (jailln) [reply src/Layer/C3DTilesLayer.js:319]: I kept the existing logic but you're right it could be simplified (also `count` becomes useluss in this case). However, as the `C3DTilesStyle` widget is broken (#2267) I'd rather not do this in this PR because I cannot test my modifications.

File: src/Core/3DTiles/C3DTFeature.js (hunk 4 above)
Comment (Desplandis) [reply src/Core/3DTiles/C3DTFeature.js:39]: Agreed with the breaking change! We should keep C3DTFeature exposed for now, it may be the object of another PR.

File: src/Layer/C3DTilesLayer.js (hunk 5 above)
Comment (Desplandis) [reply src/Layer/C3DTilesLayer.js:238]: I think we'll go for the first option.

File: src/Layer/C3DTilesLayer.js (hunk 6 above)
Comment (Desplandis) [reply src/Layer/C3DTilesLayer.js:319]: We are missing test cases here... Could you add a notice here and fix this code when #2267 is fixed?

Comment (jailln) [reply src/Layer/C3DTilesLayer.js:319]: Yep agreed... Done, I also added a notice in #2267

**Review by Desplandis — APPROVED** [review]
Previous comments were all resolved. Ready to merge!
