### PR TITLE
fix(View): fix picking radius with polygons

### LINKED ISSUE #1758: `pickFeatureAt` radius parameter
The radius parameter of the `View.pickFeatureAt` method isn't taken into account with the polygons. 
It's always 0.

### PR DESCRIPTION
**Pull request by mgermerie**
## Description

Fix picking method to take radius into acount when picking a polygon.

## Motivation and Context

Fixes #1758.

### CODE REVIEW

File: src/Utils/FeaturesUtils.js [hunk 1]
```diff
@@ -78,13 +78,14 @@ function pointIsInsidePolygon(point, polygonPoints, offset, count, size) {
...
     // in first j is last point of polygon
     // for each segment of the polygon (j is i -1)
-    // debugger;
     for (let i = offset, j = offset + count - size; i < offset + count; j = i, i += size) {
         const xi = polygonPoints[i];
         const yi = polygonPoints[i + 1];
         const xj = polygonPoints[j];
         const yj = polygonPoints[j + 1];
 
+        if (pointIsOverLine(point, [xi, yi, xj, yj], epsilon, 0, 4, 2)) { return true; }
```
Comment (gchoqueux) [inline src/Utils/FeaturesUtils.js:87]: could you replace hard values?

Comment (gchoqueux) [reply src/Utils/FeaturesUtils.js:87]: ok, the size is always 2

**Review by gchoqueux — APPROVED** [review]
