### PR TITLE
fix(core): wrong Z min and max  to compute tile's obb

### LINKED ISSUE #844: Wrong Tile OBB  with DTM
The size of tile OBB are wrong with DTM

bbox

## Expected Behavior
the box should be the size of tile

## Possible Cause/Fix/Solution
The min and max elevation aren't computed (with xbilParser). The calculation must be do for each elevation texture assigned to a tile

### PR DESCRIPTION
**Pull request by gchoqueux**
fix(core): wrong Z min and max  to compute tile's obb
because the offset/pitch was it was not taken into account

fix #844

### CODE REVIEW

File: src/Process/LayeredMaterialNodeProcessing.js [hunk 1]
```diff
@@ -254,12 +254,16 @@ export function updateLayeredMaterialNodeElevation(context, layer, node, parent)
...
-            node.setBBoxZ(min, max);
+        if (nodeLayer.textures[0]) {
+            if (!useMinMaxFromParent) {
+                const { min, max } =  computeMinMaxElevation(
+                    nodeLayer.textures[0].image.data,
+                    SIZE_TEXTURE_TILE, SIZE_TEXTURE_TILE,
+                    nodeLayer.offsetScales[0]);
+                node.setBBoxZ(min, max);
+            } else {
+                // TODO: to verify we don't pass here
```
Comment (zarov) [inline src/Process/LayeredMaterialNodeProcessing.js]: TODO when ? Specify a release if its meant to be done later, and open an issue about it.

Comment (gchoqueux) [reply src/Process/LayeredMaterialNodeProcessing.js]: i open #1011

**Review by zarov — APPROVED** [review]
Thanks !
