### PR TITLE
Fix obb 3d tiles

### LINKED ISSUE #656: Wrong calculation 3dtiles's OBB
## Your Environment
all browsers and all os 

## Context
Wrong position/size for 3dtiles's OBB

## Possible Cause/Fix/Solution
possible cause : `OBB.extentToOBB` and `OBB.cardinalsXYZToOBB`

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description
fix wrong 3dtiles's OBB using BuilderEllipsoidTile fix #656
fix wrong cachekey value equal to NaN in geometry tile building

## Screenshots (if appropriate)
obb

### CODE REVIEW

File: src/Renderer/ThreeExtended/OBB.js [hunk 1]
```diff
@@ -103,119 +105,28 @@ for (let i = 0; i < 9; i++) {
 }
 
 // get oriented bounding box of tile
-OBB.extentToOBB = function extentToOBB(extent, minHeight = 0, maxHeight = 0) {
+const builder = new BuilderEllipsoidTile();
+OBB.extent_R4326_ToOBB_4978 = function _extent_R4326_ToOBB_4978(extent, minHeight = 0, maxHeight = 0) {
```
Comment (peppsac) [inline src/Renderer/ThreeExtended/OBB.js]: You don't need to rename the function; but you need to add a check at the beginning to validate `extent._internalStorageUnit`

File: src/Renderer/ThreeExtended/OBB.js [hunk 2]
```diff
@@ -103,119 +105,28 @@ for (let i = 0; i < 9; i++) {
...
-    obb.lookAt(tmp.normal);
-    obb.translateX(tmp.translate.x);
-    obb.translateY(tmp.translate.y);
-    obb.translateZ(tmp.translate.z);
-
-    // for 3D
-    if (minHeight !== 0 || maxHeight !== 0) {
-        obb.translateZ(-halfMaxHeight + minHeight + nHalfSize);
-    }
+    const { sharableExtent, quaternion, position } = builder.computeSharableExtent(extent);
```
Comment (peppsac) [inline src/Renderer/ThreeExtended/OBB.js]: Building a new tile to then build the OBB seems a bit overkill but at least it's a major code simplification, so +1

File: src/Renderer/ThreeExtended/OBB.js [hunk 3]
```diff
@@ -103,119 +105,28 @@ for (let i = 0; i < 9; i++) {
...
+        segment: 2,
+        disableSkirt: true,
+    };
+
+    const geometry = new TileGeometry(paramsGeometry, builder);
+    const obb = geometry.OBB;
+    obb.updateZ(minHeight, maxHeight);
+    obb.position.copy(position);
+    obb.quaternion.copy(quaternion);
+    obb.update();
```
Comment (peppsac) [inline src/Renderer/ThreeExtended/OBB.js:130]: `geometry.dispose()` must be called before leaving the function to allow threejs to release the associated memory.

**Review by peppsac — COMMENTED** [review]
Looks good overall, just a few minor comments to fix before merging.

File: src/Renderer/ThreeExtended/OBB.js (hunk 3 above)
Comment (gchoqueux) [reply src/Renderer/ThreeExtended/OBB.js:130]: I'm not sure because geometry was not pushed in rendering

File: src/Renderer/ThreeExtended/OBB.js (hunk 1 above)
Comment (gchoqueux) [reply src/Renderer/ThreeExtended/OBB.js]: ok

Comment (gchoqueux) [reply src/Renderer/ThreeExtended/OBB.js]: done

File: src/Renderer/ThreeExtended/OBB.js (hunk 3 above)
Comment (peppsac) [reply src/Renderer/ThreeExtended/OBB.js:130]: Yes it's useless for now.
But it doesn't hurt to add it in case threejs change its behavior and begin reserving some memory at creation time.

(or don't add it but add a comment stating something like "Calling geometry.dispose() is not needed since this geometry never gets rendered")

Comment (gchoqueux) [reply src/Renderer/ThreeExtended/OBB.js:130]: comment added

**Review by peppsac — APPROVED** [review]
LGTM (don't forget to cleanup your commits before merging)
