### PR TITLE
Refacto geojson parsing and converting features

### LINKED ISSUE #731: Performance, very slow (5 FPS), in globe WFS extruded example, since hole support
The globe WFS extruded example is very slow since hole support.

## Steps to Reproduce (for bugs)
1. Start FPS Meter on Chrome : console -> Rendering -> FPS meter
2. Try the code before hole support
git checkout 2de6ba7a66b5332dec0bc35cb067eeae50818f8d
3. Check the WFS Extruded example.
It shows between 40 and 60 FPS
4. Try the code after the hole support
git checkout a212dde70542b2a4480eb064df45820cad847363
5. WFS Extruded example shows between 3 and 8 FPS

## Expected Behavior
The examples should give a good user experience.

## Actual Behavior
The globe WFS extruded example is very hard to use, the computer seems to freeze.

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description
**Refacto `GeojsonParser,` `Feature2Mesh` and `feature2texture`** 

- add merge features option (so the convert creates only one mesh) 
- Use one array of number to store the coordinates

**BREAKING CHANGE**
One array of number to store the coordinates instead of array of coordinates

## Motivation and Context
- **fix #731 bad performance**

   - Before bug from PR #691, total time by functions are :
     - ` geojsonParser.parse`  320 ms
     - `feature2Mesh`  216 ms
         `parse + convert` 536 ms
     - `renderScene` 350 ms
     - **total** 866 ms

   - From introduction of bug with PR #691, total time by functions are :
     - ` geojsonParser.parse`  874 ms (x 2.7 slower)
     - `feature2Mesh`  451 ms (x 2.1 slower)
        `parse + convert ` 1325 ms (x 2.5 slower)
     - `renderScene` 885 ms (x 2.5 slower)
     - **total** 2210 ms (x 2.5 slower)

   - After fix from this PR, total time by functions are :
     - ` geojsonParser.parse`  90 ms (x 10 faster)
     - `feature2Mesh`  115 ms (x 4 faster)
        `parse + convert ` 205 ms (x 6.5 faster)
     - `renderScene` 314 ms (x 2.8 faster)
     - **total** 724 ms (x 3 faster)

- **ref: Improving the Feature type #763**

### CODE REVIEW

**Comment by gliegard** [comment]
Great performance fix !!

**Comment by gchoqueux** [comment]
i must fix GUI pixel and line size

File: src/Parser/GeoJsonParser.js [hunk 1]
```diff
@@ -159,58 +169,121 @@ function readGeometry(feature, crsIn, crsOut, geometry, filteringExtent, options
...
     }
+
+    if (options.mergeFeatures) {
+        for (const type of mergesType) {
+            const f = featuresMerge[type];
+            if (f.geometry.length) {
+                f.vertices.crs = crsOut;
+                res.features.push(f);
+                if (options.buildExtent) {
+                    mergeExtent(res, f.extent);
```
Comment (zarov) [inline src/Parser/GeoJsonParser.js:280]: Not necessary, it should already be at the maximum extent at this point, no ?

File: src/Parser/GeoJsonParser.js [hunk 2]
```diff
@@ -29,118 +21,136 @@ function readCRS(json) {
...
 }
 
 // Helper struct that returns an object { type: "", coordinates: [...], extent}:
 // - type is the geom type
 // - Coordinates is an array of Coordinate
 // - extent is optional, it's coordinates's extent
 // Multi-* geometry types are merged in one.
+const coords = new Coordinates('EPSG:4978', 0, 0, 0);
+// filter with the first point
+const firstPtIsOut = (extent, aCoords, crs) => {
```
Comment (zarov) [inline src/Parser/GeoJsonParser.js:82]: Filtering on the first point is kind of arbitrary, what can you propose instead ?

File: src/Provider/DataSourceProvider.js [hunk 3]
```diff
@@ -47,14 +47,17 @@ function fetchData(url, format, networkOptions, extentSource) {
...
         crsIn: layer.source.projection,
         crsOut: layer.projection,
         // TODO FIXME: error in filtering vector tile
         // filteringExtent: extentDestination.as(layer.projection),
         filteringExtent: layer.type === 'geometry' ? extentDestination : undefined,
         filter: layer.filter,
         origin: layer.source.origin,
+        mergeFeatures: layer.mergeFeatures === undefined ? true : layer.mergeFeatures,
+        withNormal: layer.type === 'geometry',
+        withAltitude: layer.type === 'geometry',
```
Comment (zarov) [inline src/Provider/DataSourceProvider.js:60]: What if I have a plane view with no altitude but still geometry data to show ?

File: src/Renderer/ThreeExtended/Feature2Mesh.js [hunk 4]
```diff
@@ -41,23 +44,25 @@ function fillColorArray(colors, length, r, g, b, offset) {
...
  */
-const vec = new THREE.Vector3();
-function coordinatesToVertices(contour, altitude, target, offset = 0, extrude = undefined) {
-    // loop over contour coodinates
-    for (let i = 0; i < contour.length; i++) {
-        const coordinate = contour[i];
-        // convert coordinate to position
-        coordinate.xyz(vec);
+const coord = new Coordinates('EPSG:4326', 0, 0);
+function coordinatesToVertices(ptsIn, normals, target, altitude = 0, extrude = 0, offsetOut = 0, countIn = ptsIn.length / 3, startIn = offsetOut) {
```
Comment (zarov) [inline src/Renderer/ThreeExtended/Feature2Mesh.js:53]: Please quickly complete the documentation above

File: src/Renderer/ThreeExtended/Feature2Mesh.js [hunk 5]
```diff
@@ -41,23 +44,25 @@ function fillColorArray(colors, length, r, g, b, offset) {
...
+    startIn *= 3;
+    countIn *= 3;
+    offsetOut *= 3;
+    const endIn = startIn + countIn;
+    for (let i = startIn, j = offsetOut; i < endIn; i += 3, j += 3) {
+        let a = 0;
+        a = !isNaN(altitude) ? altitude : altitude({}, coord.set(ptsIn.crs, ptsIn[i], ptsIn[i + 1], ptsIn[i + 2]));
```
Comment (zarov) [inline src/Renderer/ThreeExtended/Feature2Mesh.js]: No more support for an array of altitude ? We may need to find a solution to have both a value, an array or a function for those properties (in another issue).

File: src/Renderer/ThreeExtended/Feature2Mesh.js [hunk 6]
```diff
@@ -79,168 +84,223 @@ function coordinatesToVertices(contour, altitude, target, offset = 0, extrude =
...
+        let i = 0;
         // Multi line case
         for (const geometry of feature.geometry) {
+            const color = getProperty('color', options, randomColor, geometry.properties);
             const start = geometry.indices[0].offset;
-            const end = start + geometry.indices[0].count;
-            for (let j = start; j < end; j++) {
-                indices.push(j);
-                indices.push(j + 1);
+            if (start > 0xffff) {
```
Comment (zarov) [inline src/Renderer/ThreeExtended/Feature2Mesh.js:167]: Why can't it go further ?

File: src/Renderer/ThreeExtended/Feature2Mesh.js [hunk 7]
```diff
@@ -79,168 +84,223 @@ function coordinatesToVertices(contour, altitude, target, offset = 0, extrude =
...
-    return new THREE.Points(geom);
+    return new THREE.Points(geom, pointMaterial);
 }
 
-function featureToLine(feature, properties, options) {
-    // get altitude / color from properties
-    const altitude = getProperty('altitude', options, 0, properties, feature.vertices);
-    const color = getProperty('color', options, randomColor, properties);
+var lineMaterial = new THREE.LineBasicMaterial({ vertexColors: THREE.VertexColors });
+function featureToLine(feature, options) {
```
Comment (zarov) [inline src/Renderer/ThreeExtended/Feature2Mesh.js:147]: Sidenote: we should move to `THREE.MeshLine` to have correct line width support under Angle.

File: src/Renderer/ThreeExtended/Feature2Mesh.js [hunk 8]
```diff
@@ -79,168 +84,223 @@ function coordinatesToVertices(contour, altitude, target, offset = 0, extrude =
...
     geom.setIndex(new THREE.BufferAttribute(new Uint16Array(indices), 1));
-    return new THREE.Mesh(geom);
+
+    const mesh = new THREE.Mesh(geom, material);
+    mesh.minAltitude = vertices.minAltitude;
+    return mesh;
 }
 
+function area(contour, offset, count) {
+    // Fix me: not the same result with THREE.shapeUtils.area
```
Comment (zarov) [inline src/Renderer/ThreeExtended/Feature2Mesh.js]: This needs to be fixed before merging

File: src/Renderer/ThreeExtended/Feature2Texture.js [hunk 9]
```diff
@@ -71,17 +74,21 @@ function drawPoint(ctx, vertice, origin, scale, style = {}) {
...
-    const properties = feature.properties;
-
-    if (typeof (style) == 'function') {
-        style = style(properties, feature);
-    }
-
     for (const geometry of feature.geometry) {
+        const properties = geometry.properties;
+
+        let gStyle = style;
```
Comment (zarov) [inline src/Renderer/ThreeExtended/Feature2Texture.js]: This could be reverted outside of the loop

File: test/unit/geojson.js [hunk 10]
```diff
@@ -16,12 +16,12 @@ function parse(geojson) {
 describe('GeoJsonParser', function () {
```
Comment (zarov) [inline test/unit/geojson.js:16]: Could you add some tests with maybe more features, but testing with all the new options or not in it ?

**Review by zarov — CHANGES_REQUESTED** [review]
Good work, it is going quite faster, and it is appreciated !

File: src/Parser/GeoJsonParser.js (hunk 1 above)
Comment (gchoqueux) [reply src/Parser/GeoJsonParser.js:280]: With `options.mergeFeatures`, there are finally 3 features (one multiline, multipoint and multipolygon) with one extent for each feature. But, It's necessary to compute the global extent, which is the merger of the 3 extents.

File: src/Parser/GeoJsonParser.js (hunk 2 above)
Comment (gchoqueux) [reply src/Parser/GeoJsonParser.js:82]: It's a choice. But we must filter the features that are partially on the extent. We added, later, adding filtering options.

File: src/Provider/DataSourceProvider.js (hunk 3 above)
Comment (gchoqueux) [reply src/Provider/DataSourceProvider.js:60]: you still need an altitude of zero

File: src/Renderer/ThreeExtended/Feature2Mesh.js (hunk 4 above)
Comment (gchoqueux) [reply src/Renderer/ThreeExtended/Feature2Mesh.js:53]: added

File: src/Renderer/ThreeExtended/Feature2Mesh.js (hunk 5 above)
Comment (gchoqueux) [reply src/Renderer/ThreeExtended/Feature2Mesh.js]: support added

File: src/Renderer/ThreeExtended/Feature2Mesh.js (hunk 6 above)
Comment (gchoqueux) [reply src/Renderer/ThreeExtended/Feature2Mesh.js:167]: To avoid integer overflow with indice value (16 bits), I added comment

File: src/Renderer/ThreeExtended/Feature2Mesh.js (hunk 7 above)
Comment (gchoqueux) [reply src/Renderer/ThreeExtended/Feature2Mesh.js:147]: yes, I agree

File: src/Parser/GeoJsonParser.js (hunk 1 above)
Comment (zarov) [reply src/Parser/GeoJsonParser.js:280]: Ok, missed a condition above that !

File: src/Parser/GeoJsonParser.js (hunk 2 above)
Comment (zarov) [reply src/Parser/GeoJsonParser.js:82]: Ok if it's overwritten, but we can improve this point in the future for sure.

File: src/Provider/DataSourceProvider.js (hunk 3 above)
Comment (zarov) [reply src/Provider/DataSourceProvider.js:60]: Yes

File: src/Renderer/ThreeExtended/Feature2Texture.js (hunk 9 above)
Comment (gchoqueux) [reply src/Renderer/ThreeExtended/Feature2Texture.js]: that is to say? 
`properties` may change each step

File: src/Renderer/ThreeExtended/Feature2Mesh.js (hunk 6 above)
Comment (zarov) [reply src/Renderer/ThreeExtended/Feature2Mesh.js:167]: Ok, maybe you can add a warning that the geometry is too large or something like that

File: src/Renderer/ThreeExtended/Feature2Texture.js (hunk 9 above)
Comment (zarov) [reply src/Renderer/ThreeExtended/Feature2Texture.js]: Yes indeed if `style` is a function, but you can declare `gStyle = style` outside the loop

File: src/Renderer/ThreeExtended/Feature2Mesh.js (hunk 8 above)
Comment (gchoqueux) [reply src/Renderer/ThreeExtended/Feature2Mesh.js]: sorry, it was old comment, it was already fixed

File: test/unit/geojson.js (hunk 10 above)
Comment (gchoqueux) [reply test/unit/geojson.js:16]: tests unit added

**Comment by gchoqueux** [comment]
Branch is rebased

File: src/Renderer/ThreeExtended/Feature2Texture.js (hunk 9 above)
Comment (gchoqueux) [reply src/Renderer/ThreeExtended/Feature2Texture.js]: yes

**Review by zarov — APPROVED** [review]
Seems good to me, thanks for this big fix
