### PR TITLE
fix(debug): update coordinates event on mouse move

### LINKED ISSUE #935: Some debug tools don't work in planar view
Debug tools 'Debug camera' and 'debug event' don't work in planar view.

## Your Environment
* Version used: Current master, SHA1 810a7566b3e4337577bf3d137113d81d7e0576d7
* Browser Name and version: Firefox 62.0.3
* Operating System and version (desktop or mobile): Ubuntu 18.04.1 LTS

## Steps to Reproduce (for bugs)
1. Open [planar example](https://github.com/iTowns/itowns/blob/master/examples/planar.html) in your browser
2. Expand 'Debug Tools' in the menu
3. Checking one of the two following checkbox generate an error:
   * debug Camera 
   * Debug event

## Expected Behavior

The expected behavior can be seen by reproducing the above steps in the [globe WFS extruded example](https://github.com/iTowns/itowns/blob/master/examples/globe_wfs_extruded.html)

## Actual Behavior

Nothing happens when checking these checkboxes and the following errors are generated:
  * 'debug Camera' : 

```
Error: The extent crs is not a Geographic Coordinates (EPSG:4326) itowns.js line 6652 > eval:195:15
extentToOBB
OBB.js:179
renderCameraDebug
Debug.js:165
View.prototype.execFrameRequesters
View.js:644
MainLoop.prototype._renderView
MainLoop.js:308
MainLoop.prototype._step
MainLoop.js:286
MainLoop.prototype.scheduleViewUpdate/<
MainLoop.js:52
```

  * 'Debug event':

`TypeError: controls is undefined[Learn More] debug.js line 4674 > eval:105:13 `

### PR DESCRIPTION
**Pull request by mgermerie**
## Description

Fixes the debug utility so that the `Event` tab in the `Debug Tools` menu displays the world coordinates under the mouse cursor. It previously used to display the world coordinates at the center of the screen.

Should the cursor be outside of the globe, the displayed longitude and latitude will be `0.000000`.

## Motivation and Context

Closes #935.

### CODE REVIEW

File: utils/debug/Debug.js [hunk 1]
```diff
@@ -101,16 +102,17 @@ function Debug(view, datDebugTool, chartDivContainer) {
     initialPosition.crs = view.referenceCrs;
 
     const getCenter = (controls && controls.getCameraTargetPosition) ? controls.getCameraTargetPosition : () => view.camera.camera3D.position;
-    const cameraTargetListener = () => {
-        initialPosition.setFromVector3(getCenter()).as('EPSG:4326', geoPosition);
+    const cameraTargetListener = (event) => {
+        initialPosition.setFromVector3(
+            view.getPickingPositionFromDepth(view.eventToViewCoords(event)) || new THREE.Vector3(),
```
Comment (gchoqueux) [inline utils/debug/Debug.js]: could you replace `undefined` picking by `not Number` value like `-`?

Comment (mgermerie) [reply utils/debug/Debug.js]: I changed it. Now the coordinates will display `---------` if undefined.

**Review by gchoqueux — APPROVED** [review]
