### PR TITLE
FeatureCollection local system and Style GeometryLayer.

### LINKED ISSUE #1330: Feature2Mesh.convert and Altitute function option
In `Feature2Mesh.convert`, it's possible to add callback to get altitude when mesh is built.

But this callback doesn't work the same way if we're building point, line or polygon.

It's necessary to unify the behaviours and in particular to be able to acquire the altitudes in the `properties`.

### LINKED ISSUE #1596: Precision loss when adding a new color layer from a geojson
## Your Environment
* Version used: 2.30
* Browser Name and version: Windows
* Operating System and version (desktop or mobile): desktop
* Link to your project: PackO

## Context

I'm trying to add a new Layer from a GeoJson in Lambert83 and the resulting layer has a wrong positioning for the y axes.

image

le polygone vert et le fond rouge devraient être superposable. 
On peut aussi remarquer sur le polygone orange qui devrait être continu que seuls des segments verticaux sont représentés (j'ai utilisé une width: 3)

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description
* Use local system to store `FeatureCollection` Coordinates. 
* Use `GeometryLayer` Style instead of `layer.convert` options.
* The altitude coordinates is determined in `FeatureCollection` during parsing phase (instead of Converting phase).
* the altitude maximum and minimum are computed  during parsing phase.

## Motivation
* the local system avoids precision issue (fix  #1596)
* The mesh vertices are directly in good system, and there is not a new transformation.
* the `FeatureCollection` local system axes are **East, North, Up (ENU)**  [Axes conventions](https://en.wikipedia.org/wiki/Axes_conventions).
* Unify altitude coordinates determining  (fix #1330).
* Using `Function` to define properties Style (in `ColorLayer` and `GeometricLayer`)

## WIP
- [x] fix raster picking color.

## BREAKING CHANGES
* `GeometryLayer.convert` options are moved in Style properties. Use  
  * `Style.xxx.color`
  * `Style.xxx.base_altitude`
  * `Style.fill.extrusion_height`
  * `Style.stroke.width`
  * `Style.point.radius`
* `overrideAltitudeInToZero` layer options is removed use `Style.xxx.base_altitude` instead.

#### Local system 
image

#### Use `function` to style `ColorLayer`
image

### CODE REVIEW

File: src/Converter/Feature2Mesh.js [hunk 1]
```diff
@@ -502,10 +477,23 @@ export default {
...
+        deprecatedFeature2MeshOptions(options);
         return function _convert(collection) {
             if (!collection) { return; }
 
-            return featuresToThree(collection.features, options);
+            const features = collection.features;
+
+            if (!features || features.length == 0) { return; }
+
+            const group = new THREE.Group();
```
Comment (mgermerie) [inline src/Converter/Feature2Mesh.js:467]: Here you create a `Group` without 'cleaning' the other previous groups.

**Comment by mgermerie** [comment]
Could you specify in doc that if no altitude is in the data, the objects altitude is set to `0` ?

File: examples/source_file_gpx_3d.html [hunk 2]
```diff
@@ -72,38 +71,37 @@
...
-                    .then(function (mesh) {
+                    .then(collection => {
+                        collection.setParentStyle(new itowns.Style({
+                            stroke : {
+                                color: 'red',
+                                width: 2,
+                            },
+                            point : {
+                                color: 'white',
+                            }
```
Comment (mgermerie) [inline examples/source_file_gpx_3d.html]: Maybe the style definition for `points` could be removed, since the points are hidden under the meshes.

File: examples/source_stream_wfs_25d.html [hunk 3]
```diff
@@ -161,13 +161,18 @@
 
             var lyonTclBusLayer = new itowns.GeometryLayer('lyon_tcl_bus', new itowns.THREE.Group(), {
                 update: itowns.FeatureProcessing.update,
-                convert: itowns.Feature2Mesh.convert({
-                    color: colorLine,
-                    altitude: altitudeLine }),
-                onMeshCreated: setMaterialLineWidth,
```
Comment (mgermerie) [inline examples/source_stream_wfs_25d.html:167]: Could you remove the method `setMaterialLineWidth` (from line 104 to line 110) ?  I believe it is no longer used in the example.

File: examples/source_stream_wfs_25d.html [hunk 4]
```diff
@@ -230,19 +235,26 @@
...
-                    extrude: extrudeBuildings }),
+                    batchId: function (property, featureId) { return featureId; }
+                }),
                 onMeshCreated: function scaleZ(mesh) {
-                    mesh.scale.z = 0.01;
-                    meshes.push(mesh);
+                    mesh.children.forEach(c => {
+                        c.scale.z = 0.01;
+                        meshes.push(c);
+                    })
```
Comment (mgermerie) [inline examples/source_stream_wfs_25d.html:231]: For my information : is this part combined with the `scaler` method defined from lines 199 to 212 responsible for the buildings 'rising from the ground' effect ?

Comment (mgermerie) [reply examples/source_stream_wfs_25d.html:231]: Also : what is the difference between applying a scale to the whole meshes group instead of applying it individualy to each mesh within the group ?

File: examples/view_immersive.html [hunk 5]
```diff
@@ -135,10 +135,14 @@
...
                 var wfsBuildingLayer = new itowns.GeometryLayer('Buildings', new itowns.THREE.Group(), {
                     update: itowns.FeatureProcessing.update,
-                    convert: itowns.Feature2Mesh.convert({
-                        altitude: altitudeBuildings,
-                        extrude: extrudeBuildings }),
-
+                    convert: itowns.Feature2Mesh.convert(),
+                    style: new itowns.Style({
+                        fill: {
+                            color: () => new itowns.THREE.Color(0xbbffbb),
```
Comment (mgermerie) [inline examples/view_immersive.html]: Why is a method passed for the color ? I believe it could simply be `color: new itowns.THREE.Color(0xbbffbb)`, or even no color at all.

File: src/Core/Deprecated/Undeprecator.js [hunk 6]
```diff
@@ -36,20 +36,41 @@ export const deprecatedParsingOptionsToNewOne = (options) => {
         }
         newOptions.out.filteringExtent = options.filteringExtent;
         newOptions.out.style = options.style;
-        newOptions.out.overrideAltitudeInToZero = options.overrideAltitudeInToZero;
+        if (options.overrideAltitudeInToZero) {
+            console.error('Parsing options out.overrideAltitudeInToZero is removed, use Style.xxx.base_altitude instead');
+        }
```
Comment (mgermerie) [inline src/Core/Deprecated/Undeprecator.js]: I believe this could be removed, since it is already implemented at lines 55 to 57.

File: src/Converter/Feature2Mesh.js [hunk 7]
```diff
@@ -136,18 +111,21 @@ function featureToPoint(feature, options) {
...
     let vertices;
-    if (options.altitude !== 0) {
+    const zTranslation = feature.altitude.min - options.GlobalZTrans;
+    if (zTranslation !== 0) {
         vertices = new Float32Array(ptsIn.length);
-        coordinatesToVertices(ptsIn, normals, vertices, options.altitude);
+        coordinatesToVertices(ptsIn, normals, vertices, zTranslation);
     } else {
         vertices = new Float32Array(ptsIn);
     }
```
Comment (mgermerie) [inline src/Converter/Feature2Mesh.js]: Could this part be replaced by the following ?
```js
vetices = new Float32Array(ptsIn);
if (zTranslation !== 0) {
    coordinatesToVertices(ptsIn, normals, vertices, zTranslation);
}
```

I believe it wouldn't change anything since the values within `vertices` are changed in `coordinatesToVertices` anyway.

File: src/Converter/Feature2Mesh.js (hunk 1 above)
Comment (gchoqueux) [reply src/Converter/Feature2Mesh.js:467]: done

**Comment by gchoqueux** [comment]
> Could you specify in doc that if no altitude is in the data, the objects altitude is set to `0` ?

documentation added

File: src/Core/Style.js [hunk 8]
```diff
@@ -137,42 +143,61 @@ function defineStyleProperty(style, category, name, value, defaultValue) {
  * @property {number} order - Order of the features that will be associated to
  * the style. It can helps sorting and prioritizing features if needed.
  * @property {Object} fill - Polygons and fillings style.
- * @property {string} fill.color - Defines the main color of the filling. Can be
+ * @property {string|function} fill.color - Defines the main color of the filling. Can be
  * any [valid color
  * string](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value).
  * Default is no value, indicating that no filling needs to be done.
- * @property {Image|Canvas|string} fill.pattern - Defines a pattern to fill the
+ * If the `Layer` is a `GeometricLayer` you could use `THREE.Color`.
```
Comment (mgermerie) [inline src/Core/Style.js]: Good addition to the doc. Could you replace `GeometricLayer` by `GeometryLayer` ?

File: src/Core/Style.js [hunk 9]
```diff
@@ -137,42 +143,61 @@ function defineStyleProperty(style, category, name, value, defaultValue) {
...
+ * If `base_altitude` is `undefined`, the original altitude is keeped and if it doesn't exist so
+ * the altitude value is setted to 0.
  *
  * @property {Object} point - Point style.
- * @property {string} point.color - The color of the point. Can be any [valid
+ * @property {string|function} point.color - The color of the point. Can be any [valid
  * color string](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value).
  * Default is no value, indicating that no point will be shown.
- * @property {number} point.radius - The radius of the point, in pixel. Default
+ * For a `GeometricLayer`, this opacity property isn't used.
```
Comment (mgermerie) [inline src/Core/Style.js]: I think this line should be removed

File: src/Parser/GeoJsonParser.js [hunk 10]
```diff
@@ -31,17 +31,12 @@ const firstPtIsOut = (extent, aCoords, crs) => {
...
+    populateGeometry(crsIn, coordinates, geometry, feature) {
         geometry.startSubGeometry(coordinates.length, feature);
-
-        const useAlti = !collection.overrideAltitudeInToZero &&
-                        collection.size == 3 &&
-                        typeof coordinates[0][2] == 'number';
-
+        coord.crs = crsIn;
         // coordinates is a list of pair [[x1, y1], [x2, y2], ..., [xn, yn]]
         for (const pair of coordinates) {
```
Comment (mgermerie) [inline src/Parser/GeoJsonParser.js]: Maybe the name `pair` is no longer adapted, since in a 3d context we have 3 coordinates

File: test/unit/featureprocess.js [hunk 11]
```diff
@@ -18,13 +19,13 @@ describe('Layer with Feature process', function () {
...
+    // function extrude() {
+    //     return 5000;
+    // }
 
-    function color() {
-        return new THREE.Color(0xffcc00);
-    }
+    // function color() {
+    //     return new THREE.Color(0xffcc00);
+    // }
```
Comment (mgermerie) [inline test/unit/featureprocess.js]: Could you remove these commented lines ?

File: src/Core/Style.js [hunk 12]
```diff
@@ -137,42 +143,61 @@ function defineStyleProperty(style, category, name, value, defaultValue) {
...
  * for how to use.
- * @property {number} fill.opacity - The opacity of the color or the
+ * @property {number|function} fill.opacity - The opacity of the color or the
  * pattern. Can be between `0.0` and `1.0`. Default is `1.0`.
- *
+ * For a `GeometricLayer`, this opacity property isn't used.
+ * @property {number|function} fill.base_altitude - `GeometryLayer` Style, defines altitude
+ * for each Coordinates.
+ * If `base_altitude` is `undefined`, the original altitude is keeped and if it doesn't exist so
+ * the altitude value is setted to 0.
```
Comment (mgermerie) [inline src/Core/Style.js]: I would rather write it as such : 
```
If `base_altitude` is `undefined`, the original altitude is kept, and if it doesn't exist then the altitude value is set to 0.
```

File: src/Core/Style.js [hunk 13]
```diff
@@ -137,42 +143,61 @@ function defineStyleProperty(style, category, name, value, defaultValue) {
...
+ * If the `Layer` is a `GeometricLayer` you could use `THREE.Color`.
+ * @property {number|function} stroke.opacity - The opacity of the line. Can be between
  * `0.0` and `1.0`. Default is `1.0`.
- * @property {number} stroke.width - The width of the line. Default is `1.0`.
+ * For a `GeometricLayer`, this opacity property isn't used.
+ * @property {number|function} stroke.width - The width of the line. Default is `1.0`.
+ * @property {number|function} stroke.base_altitude - `GeometryLayer` Style, defines altitude
+ * for each Coordinates.
+ * If `base_altitude` is `undefined`, the original altitude is keeped and if it doesn't exist so
+ * the altitude value is setted to 0.
```
Comment (mgermerie) [inline src/Core/Style.js]: I would rather write it as such : 
```
If `base_altitude` is `undefined`, the original altitude is kept, and if it doesn't exist then the altitude value is set to 0.
```

File: src/Core/Style.js [hunk 14]
```diff
@@ -137,42 +143,61 @@ function defineStyleProperty(style, category, name, value, defaultValue) {
...
+ * With a `GeometricLayer` you could use `THREE.Color`.
+ * @property {number|function} point.width - The width of the border, in pixel. Default
  * is `0.0` (no border).
- * @property {number} point.opacity - The opacity of the point. Can be between
+ * @property {number|function} point.opacity - The opacity of the point. Can be between
  * `0.0` and `1.0`. Default is `1.0`.
+ * @property {number|function} point.base_altitude - `GeometryLayer` Style, defines altitude
+ * for each Coordinates.
+ * If `base_altitude` is `undefined`, the original altitude is keeped and if it doesn't exist so
+ * the altitude value is setted to 0.
```
Comment (mgermerie) [inline src/Core/Style.js]: I would rather write it as such : 
```
If `base_altitude` is `undefined`, the original altitude is kept, and if it doesn't exist then the altitude value is set to 0.
```

File: src/Core/Style.js [hunk 15]
```diff
@@ -137,42 +143,61 @@ function defineStyleProperty(style, category, name, value, defaultValue) {
...
- * @property {number} point.radius - The radius of the point, in pixel. Default
+ * For a `GeometricLayer`, this opacity property isn't used.
+ * @property {number|function} point.radius - The radius of the point, in pixel. Default
  * is `2.0`.
- * @property {string} point.line - The color of the border of the point. Can be
+ * @property {string|function} point.line - The color of the border of the point. Can be
  * any [valid color
  * string](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value).
- * @property {number} point.width - The width of the border, in pixel. Default
+ * With a `GeometricLayer` you could use `THREE.Color`.
```
Comment (mgermerie) [inline src/Core/Style.js]: You should instead specify that `point.line` is not supported with a `GeometryLayer`.

File: examples/source_stream_wfs_25d.html (hunk 3 above)
Comment (gchoqueux) [reply examples/source_stream_wfs_25d.html:167]: removed

File: examples/source_stream_wfs_25d.html (hunk 4 above)
Comment (gchoqueux) [reply examples/source_stream_wfs_25d.html:231]: > For my information : is this part combined with the scaler method defined from lines 199 to 212 responsible for the buildings 'rising from the ground' effect ?

yes

Comment (gchoqueux) [reply examples/source_stream_wfs_25d.html:231]: > Also : what is the difference between applying a scale to the whole meshes group instead of applying it individually to each mesh within the group ?

because the mesh `Feature` is added to new `Group`.

but yes you're right, it's not very intuitive
I will look for a way to avoid this

File: examples/view_immersive.html (hunk 5 above)
Comment (gchoqueux) [reply examples/view_immersive.html]: yes, i removed it

File: src/Core/Deprecated/Undeprecator.js (hunk 6 above)
Comment (gchoqueux) [reply src/Core/Deprecated/Undeprecator.js]: I changed it but i'm not sure of this part

File: src/Converter/Feature2Mesh.js (hunk 7 above)
Comment (gchoqueux) [reply src/Converter/Feature2Mesh.js]: I'm not sure, because  `new Float32Array(ptsIn.length)` is memory allocation and  `new Float32Array(ptsIn)` is memory copy.

File: src/Core/Style.js (hunk 8 above)
Comment (gchoqueux) [reply src/Core/Style.js]: yes

File: src/Core/Style.js (hunk 9 above)
Comment (gchoqueux) [reply src/Core/Style.js]: removed

File: src/Parser/GeoJsonParser.js (hunk 10 above)
Comment (gchoqueux) [reply src/Parser/GeoJsonParser.js]: yes

File: test/unit/featureprocess.js (hunk 11 above)
Comment (gchoqueux) [reply test/unit/featureprocess.js]: yes

File: src/Core/Style.js (hunk 12 above)
Comment (gchoqueux) [reply src/Core/Style.js]: yes

File: src/Core/Style.js (hunk 13 above)
Comment (gchoqueux) [reply src/Core/Style.js]: Thanks!

File: src/Core/Style.js (hunk 14 above)
Comment (gchoqueux) [reply src/Core/Style.js]: Yes, i changed it

File: src/Core/Style.js (hunk 15 above)
Comment (gchoqueux) [reply src/Core/Style.js]: yes

File: src/Core/Deprecated/Undeprecator.js (hunk 6 above)
Comment (mgermerie) [reply src/Core/Deprecated/Undeprecator.js]: Now that you added the `return newOptions` again, it shall not pass into the second verification.
Maybe you could do the following ?

```js
if (options.crsOut || options.crsIn) {
   // add all the newOptions creation but remove the 'overrideAltitudeInToZero'
   options = newOptions;
}

// add verification for 'options.out.withAltitude' and 'options.out.withNormal' as they already are implemented

if (options.overrideAltitudeInToZero) {
    console.error('error message');
}

return options;
```

File: src/Converter/Feature2Mesh.js (hunk 7 above)
Comment (mgermerie) [reply src/Converter/Feature2Mesh.js]: Ok, then its a good implementation

File: src/Core/Style.js [hunk 16]
```diff
@@ -137,42 +143,62 @@ function defineStyleProperty(style, category, name, value, defaultValue) {
...
+ * If `base_altitude` is `undefined`, the original altitude is kept, and if it doesn't exist
+ * then the altitude value is set to 0.
  *
  * @property {Object} point - Point style.
- * @property {string} point.color - The color of the point. Can be any [valid
+ * @property {string|function} point.color - The color of the point. Can be any [valid
  * color string](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value).
  * Default is no value, indicating that no point will be shown.
- * @property {number} point.radius - The radius of the point, in pixel. Default
+ * For a `GeometryLayer`, this opacity property isn't used.
```
Comment (mgermerie) [inline src/Core/Style.js]: This line could be removed too, as it mentions `opacity` property within the `color` property description.

File: examples/source_stream_wfs_25d.html (hunk 4 above)
Comment (mgermerie) [reply examples/source_stream_wfs_25d.html:231]: Ok, thanks !

File: src/Core/Style.js (hunk 16 above)
Comment (gchoqueux) [reply src/Core/Style.js]: removed

Comment (mgermerie) [reply src/Core/Style.js]: Thanks

File: src/Converter/Feature2Mesh.js [hunk 17]
```diff
@@ -1,31 +1,20 @@
 import * as THREE from 'three';
 import Earcut from 'earcut';
-import Coordinates from 'Core/Geographic/Coordinates';
 import { FEATURE_TYPES } from 'Core/Feature';
+import { deprecatedFeature2MeshOptions } from 'Core/Deprecated/Undeprecator';
 
-function getProperty(name, options, defaultValue, ...args) {
-    const property = options[name];
+const rColor = new THREE.Color();
```
Comment (mgermerie) [inline src/Converter/Feature2Mesh.js]: It's a small detail but maybe `rColor` is not the most suited name for this constant, since it is not always set to a random color.

File: src/Converter/Feature2Mesh.js [hunk 18]
```diff
@@ -188,13 +168,18 @@ function featureToLine(feature, options) {
 
     let lines;
 
+    // TODO CREATE material for each feature
```
Comment (mgermerie) [inline src/Converter/Feature2Mesh.js:170]: By this `TODO`, do you mean that the `var lineMaterial = new THREE.LineBasicMaterial();` on line 148 should later be here instead ?

File: src/Converter/Feature2Mesh.js [hunk 19]
```diff
@@ -257,14 +252,15 @@ function featureToPolygon(feature, options) {
             console.warn('Feature to Polygon: integer overflow, too many points in polygons');
             break;
         }
-        const color = getProperty('color', options, randomColor, geometry.properties);
+        const context = { globals, properties: () => geometry.properties };
+        const style = feature.style.drawingStylefromContext(context);
+
+        const color = toColor(style.fill.color);
```
Comment (mgermerie) [inline src/Converter/Feature2Mesh.js]: Maybe you don't need to create a new constant, since `color` is only used once at line 264 in `fillColorArray(colors, count, color, start);`.

Comment (mgermerie) [reply src/Converter/Feature2Mesh.js]: Also : a constant named `color` allready exists (at line 226).

File: src/Converter/Feature2Mesh.js [hunk 20]
```diff
@@ -321,31 +316,33 @@ function featureToExtrudedPolygon(feature, options) {
...
-        const extrude = getProperty('extrude', options, 0, geometry.properties);
+        const context = { globals, properties: () => geometry.properties };
+        const style = feature.style.drawingStylefromContext(context);
 
-        const colorTop = getProperty('color', options, randomColor, geometry.properties);
-        color.copy(colorTop);
-        color.multiplyScalar(0.6);
+        fillColor = toColor(style.fill.color);
+        color.copy(fillColor);
+        color.multiplyScalar(0.5);
```
Comment (mgermerie) [inline src/Converter/Feature2Mesh.js]: Maybe you could add a comment to specify that this `color` is applied to the bottom surface of extruded polygons, and that `fillColor` is applied to the top surface.

File: src/Converter/Feature2Mesh.js [hunk 21]
```diff
@@ -161,8 +139,9 @@ function featureToPoint(feature, options) {
     geom.setAttribute('color', new THREE.BufferAttribute(colors, 3, true));
     if (batchIds) { geom.setAttribute('batchId', new THREE.BufferAttribute(batchIds, 1)); }
 
+    pointMaterial.size = feature.style.point.radius;
+
     const points = new THREE.Points(geom, pointMaterial);
```
Comment (mgermerie) [inline src/Converter/Feature2Mesh.js]: You don't need to declare a constant here. You could simply put : 
```js
return new THREE.Points(geom, pointMaterial);
```

File: src/Converter/Feature2Mesh.js [hunk 22]
```diff
@@ -293,7 +289,6 @@ function featureToPolygon(feature, options) {
     geom.setIndex(new THREE.BufferAttribute(new Uint16Array(indices), 1));
 
     const mesh = new THREE.Mesh(geom, material);
```
Comment (mgermerie) [inline src/Converter/Feature2Mesh.js]: Same as in `featureToPoint` method : you don't need a constant declaration here and you could simply put : 
```js
return new THREE.Mesh(geom, material);
```

File: src/Core/Feature.js [hunk 23]
```diff
@@ -148,6 +168,11 @@ export class FeatureGeometry {
         if (this._currentExtent) {
             this._currentExtent.expandByValuesCoordinates(long, lat, alt);
```
Comment (mgermerie) [inline src/Core/Feature.js]: The method `Extent.expandByValuesCoordinates` does not take an altitude parameter.

File: src/Core/Feature.js [hunk 24]
```diff
@@ -321,6 +370,59 @@ export class FeatureCollection extends THREE.Object3D {
...
+        };
+    }
+
+    /**
+     * Apply the matrix World inverse on the coordinates.
+     * This method is used when the coordinates is pushed
+     * to transform it in local system.
+     *
+     * @param   {Coordinates}  coordinates  The coordinates
+     * @returns {Coordinates} The coordinates in local sytem
```
Comment (mgermerie) [inline src/Core/Feature.js]: Could you replace `sytem` by `system` ?

File: test/unit/dataSourceProvider.js [hunk 25]
```diff
@@ -96,7 +97,7 @@ describe('Provide in Sources', function () {
         featureCountByCb = fc.features.length;
     };
 
-    featureLayer.convert = Feature2Mesh.convert({ color, extrude });
+    featureLayer.convert = Feature2Mesh.convert();
```
Comment (mgermerie) [inline test/unit/dataSourceProvider.js]: The `convert` property could be declared inside of `GeometryLayer` constructor call (at line 75 for example).

File: test/unit/featureUtils.js [hunk 26]
```diff
@@ -12,13 +12,15 @@ describe('FeaturesUtils', function () {
     it('should correctly parse geojson', () =>
         promise.then((collection) => {
             assert.equal(collection.features.length, 3);
+            collection.updateMatrix();
```
Comment (mgermerie) [inline test/unit/featureUtils.js]: Is it mandatory to test the `updateMatrix` method ? If the object returned by the `GeoJsonParser.parse` method has the property tested above (`collection.features.lenght`), that means it must be an instance of `FeatureCollection`. Therefore, it also is an instance of `Three.Object3d`. Testing the `updateMatrix` method appears to be testing Threejs.

Moreover, this `collection` object is not used later in the scope of the `promise.then`, so I don't get the point of this line.

Am I missing something ?

File: test/unit/geojson.js [hunk 27]
```diff
@@ -17,12 +17,12 @@ function parse(geojson) {
 describe('GeoJsonParser', function () {
     it('should set all z coordinates to 1', () =>
         parse(holes).then((collection) => {
-            assert.ok(collection.features[0].vertices.every((v, i) => i == 0 || ((i + 1) % 3) != 0 || v == 0));
+            assert.ok(collection.features[0].vertices.every((v, i) => i == 0 || ((i + 1) % 3) != 0 || (v + collection.position.z) == 0));
```
Comment (mgermerie) [inline test/unit/geojson.js]: The condition `i == 0` could be removed, since when this condition is true, the second condition (`(i + 1) % 3 != 0`) is always true as well.

The same goes for the line 25.

File: test/unit/geojson.js [hunk 28]
```diff
@@ -17,12 +17,12 @@ function parse(geojson) {
 describe('GeoJsonParser', function () {
     it('should set all z coordinates to 1', () =>
```
Comment (mgermerie) [inline test/unit/geojson.js]: Unless I'm missing something, shouldn't this description be `'should set all z coordinates to 0'` ?

File: src/Converter/Feature2Mesh.js (hunk 17 above)
Comment (gchoqueux) [reply src/Converter/Feature2Mesh.js]: yes

File: src/Converter/Feature2Mesh.js (hunk 18 above)
Comment (gchoqueux) [reply src/Converter/Feature2Mesh.js:170]: it needs of new PR

File: src/Converter/Feature2Mesh.js (hunk 19 above)
Comment (gchoqueux) [reply src/Converter/Feature2Mesh.js]: yes, I change it

File: src/Converter/Feature2Mesh.js (hunk 20 above)
Comment (gchoqueux) [reply src/Converter/Feature2Mesh.js]: added

**Comment by gchoqueux** [comment]
@mgermerie  thanks for the review !
I push a new version

File: src/Converter/Feature2Mesh.js [hunk 29]
```diff
@@ -411,7 +404,7 @@ function featureToMesh(feature, options) {
             mesh = featureToLine(feature, options);
             break;
         case FEATURE_TYPES.POLYGON:
-            if (options.extrude) {
+            if (feature.style.fill.extrusion_height) {
```
Comment (mgermerie) [inline src/Converter/Feature2Mesh.js:404]: Could you change the doc for the `featureToMesh` method ?  It still mentions `options.altitude`, `options.extrude` and `options.color`.

File: src/Core/Deprecated/Undeprecator.js [hunk 30]
```diff
@@ -29,27 +29,48 @@ export const deprecatedParsingOptionsToNewOne = (options) => {
         newOptions.out.mergeFeatures = options.mergeFeatures;
         newOptions.out.withNormal = options.withNormal;
         newOptions.out.withAltitude = options.withAltitude;
```
Comment (mgermerie) [inline src/Core/Deprecated/Undeprecator.js]: Is there a point in copying `options.withNormal` and `options.withAltitude` parameters in `newOptions` since both these parameters are deprecated ?
Maybe you could instead remove lines 30 and 31, and replace line 32 by : 
```js
if (options.withAltitude && options.withNormal)
```

File: src/Core/Deprecated/Undeprecator.js [hunk 31]
```diff
@@ -29,27 +29,48 @@ export const deprecatedParsingOptionsToNewOne = (options) => {
...
+            console.error('Parsing options out.overrideAltitudeInToZero is removed, use Style.xxx.base_altitude instead');
+        }
         newOptions.out.filter = options.filter;
         return newOptions;
-    } else if (options.out && (options.out.withAltitude !== undefined || options.out.withNormal !== undefined)) {
-        console.warn('Parsing options out.withAltitude and out.withNormal are deprecates, use out.structure: 2d or 3d.');
+    }
+
+    if (options.out && (options.out.withAltitude !== undefined || options.out.withNormal !== undefined)) {
+        console.warn('Parsing options out.withAltitude and out.withNormal are deprecated, use out.structure: 2d or 3d.');
```
Comment (mgermerie) [inline src/Core/Deprecated/Undeprecator.js]: Could you replace 'are' by 'is' ?

File: examples/source_stream_wfs_25d.html (hunk 4 above)
Comment (gchoqueux) [reply examples/source_stream_wfs_25d.html:231]: We keep it for the moment.

**Comment by gchoqueux** [comment]
I refactor the `Undeprecator.js`, there were some issues.

File: src/Converter/Feature2Mesh.js (hunk 29 above)
Comment (mgermerie) [reply src/Converter/Feature2Mesh.js:404]: Thanks !

**Review by mgermerie — APPROVED** [review]
