### PR TITLE
fix(3dtiles): handle multiple 3dtiles

### LINKED ISSUE #2574: [REGRESSION] The example 3dtiles_loader.html can load only 1 dataset
Since https://github.com/iTowns/itowns/pull/2500 ,
The example 3dtiles_loader.html isn't not working correctly

## Steps to Reproduce

1. Load 3dtiles_loader.html
2. Switch between the different 3dtiles
3. Only the first one is loading

## Actual Behavior
Only the first chosen 3dtiles is loading

## Possible Cause/Fix/Solution
Issue coming from this part 
https://github.com/iTowns/itowns/blob/master/packages/Main/src/Layer/OGC3DTilesLayer.js#L318-L327

Could come from that in _setupCacheAndQueues we are already overwriting the queues

### PR DESCRIPTION
**Pull request by AnthonyGlt**
## Description
Handle multiple 3Dtiles in a single view.

## Motivation and Context
Fixing https://github.com/iTowns/itowns/issues/2574

Currently we are sharing the same queues and cache amongst all the OGC3DTilesLayer to improve performances
as defined here
https://github.com/NASA-AMMOS/3DTilesRendererJS?tab=readme-ov-file#multiple-tilesrenderers-with-shared-caches-and-queues

We also need to define a custom callback for the `downloadQueue` and `parseQueue` to make the updating work correctly in VR. New tile downloads were never triggered during active WebXR sessions :
https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/213#issuecomment-947943386
By doing this, we don't trigger the  `requestAnimationFrame` used in the lib 3DTilesRendererJS

The thing is that by sharing the queues, we were overwriting the callbacks for all layers at each new added layer.
The fix is that we keep track of each callback function used in all the OGC3DTilesLayers of the view

Can be tested using this custom example:

```html


<html>
<head>
    <title>Itowns - 3D Tiles loader</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="css/example.css">
    <link rel="stylesheet" type="text/css" href="css/LoadingScreen.css">
    <style type="text/css">
        #description {
            z-index: 2;
            left: 10px;
        }
        #featureInfoText {
            font-size: small;
        }
        #description .marg {
            margin: 10px;
        }
        #layersList {
            margin: 10px;
            padding: 10px;
            border: 1px solid #ccc;
            background-color: #f9f9f9;
        }
        .layer-item {
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 5px;
            margin: 5px 0;
            border: 1px solid #ddd;
            background-color: white;
        }
        .delete-btn {
            background-color: #ff4444;
            color: white;
            border: none;
            padding: 5px 10px;
            cursor: pointer;
            border-radius: 3px;
        }
        .delete-btn:hover {
            background-color: #cc0000;
        }
        .zoom-btn {
            background-color: #4444ff;
            color: white;
            border: none;
            padding: 5px 10px;
            cursor: pointer;
            border-radius: 3px;
            margin-right: 5px;
        }
        .zoom-btn:hover {
            background-color: #0000cc;
        }
    </style>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dat-gui/0.7.6/dat.gui.min.js"></script>
</head>
<body>
<div id="viewerDiv"></div>
<div id="description">Specify the URL of a tileset to load:
    <input type="text" id="url" />
    <button onclick="readURL()">Load</button>
    <div class="marg">
        <button onClick="loadLyon()">Load Lyon 1 (Mesh)</button>
        <button onClick="loadSete()">Load Sete (Point Cloud)</button>
        <button onClick="loadLille()">Load Lille (Mesh)</button>
        <div id="share"></div>
    </div>
    <hr />
    <div id="layersList">
        <h3>Loaded 3D Tiles Layers:</h3>
        <div id="layersContainer"></div>
    </div>
    <hr />
    <p id="featureInfoText" class="marg"><em>Display feature information by clicking on it</em></p>
    <p><b>Feature Information:</b></p>
    <div id="featureInfo" class="marg"></div>
</div>
<script src="js/GUI/GuiTools.js"></script>
<script src="../dist/itowns.js"></script>
<script src="js/GUI/LoadingScreen.js"></script>
<script src="../dist/debug.js"></script>
<script type="importmap">
    {
        "imports": {
            "three": "https://cdn.jsdelivr.net/npm/three@0.170.0/build/three.module.js",
            "three/addons/": "https://cdn.jsdelivr.net/npm/three@0.170.0/examples/jsm/"
        }
    }
</script>
<script type="module">
    import {
        AmbientLight,
        PMREMGenerator,
    } from 'three';
    import { MeshoptDecoder } from 'three/addons/libs/meshopt_decoder.module.js';
    import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
    import {
        zoomToLayer,
        fillHTMLWithPickingInfo,
    } from './jsm/OGC3DTilesHelper.js';
    const {
        TMSSource, WMTSSource, OGC3DTilesSource,
        ColorLayer, ElevationLayer, OGC3DTilesLayer, PNTS_SIZE_MODE,
        GlobeView, Coordinates, Fetcher,
    } = itowns;

    // Store all loaded layers
    window.layers = new Map();

    const uri = new URL(location);
    window.gui = new dat.GUI();

    // ---- Create a GlobeView ----
    const placement = {
        coord: new Coordinates('EPSG:4326', 2.351323, 48.856712),
        range: 12500000,
    };

    const viewerDiv = document.getElementById('viewerDiv');
    const view = new GlobeView(viewerDiv, placement, {
        controls: {
            minDistance: 100,
        }
    });

    // Enable various compression support for 3D Tiles tileset
    itowns.enableDracoLoader('./libs/draco/');
    itowns.enableKtx2Loader('./lib/basis/', view.renderer);
    itowns.enableMeshoptDecoder(MeshoptDecoder);

    // Add ambient light to globally illuminates all objects
    const light = new AmbientLight(0x404040, 40);
    view.scene.add(light);

    // Set the environment map for all physical materials in the scene
    const environment = new RoomEnvironment();
    const pmremGenerator = new PMREMGenerator(view.renderer);
    view.scene.environment = pmremGenerator.fromScene(environment).texture;
    pmremGenerator.dispose();

    // Setup loading screen
    setupLoadingScreen(viewerDiv, view);

    // ---- Add a basemap ----
    Fetcher.json('./layers/JSONLayers/OPENSM.json').then((config) => {
        const colorLayer = new ColorLayer('Ortho', {
            ...config,
            source: new TMSSource(config.source),
        });
        view.addLayer(colorLayer);
    });

    // ---- Add 3D terrain ----
    function addElevationLayerFromConfig(config) {
        config.source = new itowns.WMTSSource(config.source);
        var elevationLayer = new itowns.ElevationLayer(config.id, config);
        view.addLayer(elevationLayer);
    }
    itowns.Fetcher.json('./layers/JSONLayers/IGN_MNT_HIGHRES.json').then(addElevationLayerFromConfig);
    itowns.Fetcher.json('./layers/JSONLayers/WORLD_DTM.json').then(addElevationLayerFromConfig);

    // Generate unique layer ID
    function generateLayerId() {
        return '3DTiles_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9);
    }

    // Zoom to specific layer
    function zoomToSpecificLayer(layerId) {
        const layer = window.layers.get(layerId);
        if (layer) {
            zoomToLayer(view, layer);
        }
    }

    // Update layers UI
    function updateLayersUI() {
        const container = document.getElementById('layersContainer');
        container.innerHTML = '';

        window.layers.forEach((layer, layerId) => {
            const layerDiv = document.createElement('div');
            layerDiv.className = 'layer-item';
            layerDiv.innerHTML = `
                        <span>${layer.name || layerId}</span>
                        <div>
                            <button class="zoom-btn" onclick="zoomToSpecificLayer('${layerId}')">Zoom</button>
                            <button class="delete-btn" onclick="deleteLayer('${layerId}')">Delete</button>
                        </div>
                    `;
            container.appendChild(layerDiv);
        });
    }

    // Delete specific layer
    function deleteLayer(layerId) {
        const layer = window.layers.get(layerId);
        if (layer) {
            // Remove from GUI if it exists
            try {
                gui.removeFolder(`Layer ${layerId}`);
            } catch (e) {
                // Folder might not exist, ignore error
            }

            // Remove from view
            view.removeLayer(layerId);
            view.notifyChange();

            // Delete layer
            if (layer.delete) {
                layer.delete();
            }

            // Remove from our tracking
            window.layers.delete(layerId);

            // Update UI
            updateLayersUI();
        }
    }

    // ---------- 3D Tiles loading
    function readURL() {
        const url = document.getElementById('url').value;
        if (url) {
            setUrl(url);
        }
    }

    function setUrl(url) {
        if (!url) return;
        const input_url = document.getElementById('url');
        if (!input_url) return;
        uri.searchParams.set('copc', url);
        history.replaceState(null, null, `?${uri.searchParams.toString()}`);
        input_url.value = url;
        load(url);
    }

    function load(url, name = null) {
        const source = new OGC3DTilesSource({ url });
        const layerId = generateLayerId();

        const layer = new OGC3DTilesLayer(layerId, {
            source,
            pntsSizeMode: PNTS_SIZE_MODE.ATTENUATED,
        });

        // Store layer name for display
        if (name) {
            layer.name = name;
        }

        // Add an event for picking the 3D Tiles layer
        const pickingArgs = {
            htmlDiv: document.getElementById('featureInfo'),
            view,
            layer: layer,
        };

        // Add the layer to our view
        view.addLayer(layer).then((addedLayer) => {
            // Store the layer
            window.layers.set(layerId, addedLayer);

            // Update UI
            updateLayersUI();

            // Always zoom to the newly loaded layer
            zoomToLayer(view, addedLayer);

            // Add click event listener for picking
            window.addEventListener('click',
                (event) => fillHTMLWithPickingInfo(event, pickingArgs), false);
        });

        layer.whenReady.then(() => {
            debug.createOGC3DTilesDebugUI(gui, view, layer);
        });
    }

    function loadLyon() {
        const url = "https://raw.githubusercontent.com/iTowns/iTowns2-sample-data/refs/heads/master/3DTiles/lyon1-4978/tileset.json";
        load(url, "Lyon 1 (Mesh)");
    }

    function loadSete() {
        const url = "https://raw.githubusercontent.com/iTowns/iTowns2-sample-data/master/pointclouds/pnts-sete-2021-0756_6256/tileset.json";
        load(url, "Sete (Point Cloud)");
    }

    function loadLille() {
        const url = "https://webimaging.lillemetropole.fr/externe/maillage/2020_mel_5cm/tileset.json";
        load(url, "Lille (Mesh)");
    }

    // Make functions available globally
    window.readURL = readURL;
    window.loadLyon = loadLyon;
    window.loadSete = loadSete;
    window.loadLille = loadLille;
    window.deleteLayer = deleteLayer;
    window.zoomToSpecificLayer = zoomToSpecificLayer;

    // Initialize UI
    updateLayersUI();
</script>
</body>
</html>


```

### CODE REVIEW

**Comment by AnthonyGlt** [comment]
Related https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/1214

File: packages/Main/src/Layer/OGC3DTilesLayer.js [hunk 1]
```diff
@@ -335,20 +333,58 @@ class OGC3DTilesLayer extends GeometryLayer {
...
+            // (WebXR session has its own requestAnimationFrame method separate from that of the window
+            //  https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/213#issuecomment-947943386)
+            // Necessary to update rendering of the tiles in VR
+            // Example: https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/de25d27dc0e75278962b5f401faee30f8dce2fe0/example/vr.js
+            this.tilesRenderer.downloadQueue.schedulingCallback = combinedCallback;
+            this.tilesRenderer.parseQueue.schedulingCallback = combinedCallback;
         } else {
+            // Set the combined callback (cf. above comment)
+            this.tilesRenderer.downloadQueue.schedulingCallback = this.tilesSchedulingCB;
+            this.tilesRenderer.parseQueue.schedulingCallback = this.tilesSchedulingCB;
```
Comment (Desplandis) [inline packages/Main/src/Layer/OGC3DTilesLayer.js]: Would it be better to create a "combined" callback that we'll not reassign?
I imagine that such callback code will call all `viewers[id].layerCallbacks`:
```suggestion
            const combined = (func) => {
              viewers[id].layersCallbacks.forEarch((cb) => cb(func));
            }
            // Set the combined callback (cf. above comment)
            this.tilesRenderer.downloadQueue.schedulingCallback = combined;
            this.tilesRenderer.parseQueue.schedulingCallback = combined;
```

When `viewer[id]` is defined, we'll only have to add the "layer" callback to the list of `viewers[id].layerCallbacks`.

Comment (AnthonyGlt) [reply packages/Main/src/Layer/OGC3DTilesLayer.js]: Thanks for the review !

What is the difference with what it's done here :

```
   }
            viewers[id].layerCallbacks.push(this._originalSchedulingCallback);

            // Create a combined callback that calls all layer callbacks
            const combinedCallback = (func) => {
                if (viewers[id] && viewers[id].layerCallbacks) {
                    // Filter out null/undefined callbacks (from deleted layers)
                    viewers[id].layerCallbacks = viewers[id].layerCallbacks.filter(callback => callback != null);
                    viewers[id].layerCallbacks.forEach((callback) => {
                        if (callback) { callback(func); }
                    });
                }
            };
```
           
 Currently I add the cb in layerCallbacks but i also remove the ones that are null or undefined ( as a safety)

Comment (Desplandis) [reply packages/Main/src/Layer/OGC3DTilesLayer.js]: We don't have to re-assign the callback each time (see line 368-369) we add a new layer, but only once when we add new layer from a new view. It would make the code more readable I think.

File: packages/Main/src/Layer/OGC3DTilesLayer.js [hunk 2]
```diff
@@ -335,20 +333,58 @@ class OGC3DTilesLayer extends GeometryLayer {
...
+
             this.tilesRenderer.lruCache = viewers[id].lruCache;
             this.tilesRenderer.downloadQueue = viewers[id].downloadQueue;
             this.tilesRenderer.parseQueue = viewers[id].parseQueue;
+
+            // Store references to all layer callbacks for this view
+            // Each tile has it's own callback
+            if (!viewers[id].layerCallbacks) {
+                viewers[id].layerCallbacks = [];
+            }
```
Comment (Desplandis) [inline packages/Main/src/Layer/OGC3DTilesLayer.js]: Per line 379, viewers[id].layerCallbacks is never `undefined`.

File: packages/Main/src/Layer/OGC3DTilesLayer.js [hunk 3]
```diff
@@ -335,20 +333,58 @@ class OGC3DTilesLayer extends GeometryLayer {
...
+            viewers[id].layerCallbacks.push(this._originalSchedulingCallback);
+
+            // Create a combined callback that calls all layer callbacks
+            const combinedCallback = (func) => {
+                if (viewers[id] && viewers[id].layerCallbacks) {
```
Comment (Desplandis) [inline packages/Main/src/Layer/OGC3DTilesLayer.js]:
```suggestion
                if (viewers[id]?.layerCallbacks) {
```

File: packages/Main/src/Layer/OGC3DTilesLayer.js [hunk 4]
```diff
@@ -335,20 +333,58 @@ class OGC3DTilesLayer extends GeometryLayer {
...
+                    // Filter out null/undefined callbacks (from deleted layers)
+                    viewers[id].layerCallbacks = viewers[id].layerCallbacks.filter(callback => callback != null);
```
Comment (Desplandis) [inline packages/Main/src/Layer/OGC3DTilesLayer.js]: I don't think this should be necessary if we set `viewer[id].layerCallbacks[layer.id]` to undefined when removing a layer from the view.

File: packages/Main/src/Layer/OGC3DTilesLayer.js [hunk 5]
```diff
@@ -335,20 +333,58 @@ class OGC3DTilesLayer extends GeometryLayer {
...
+                    viewers[id].layerCallbacks.forEach((callback) => {
+                        if (callback) { callback(func); }
```
Comment (Desplandis) [inline packages/Main/src/Layer/OGC3DTilesLayer.js]: Same here.

File: packages/Main/src/Layer/OGC3DTilesLayer.js [hunk 6]
```diff
@@ -314,17 +314,15 @@ class OGC3DTilesLayer extends GeometryLayer {
...
             this.tasks.push(func);
         };
-        // We set our scheduling callback for tiles downloading and parsing -> MANDATORY for VR
-        // (WebXR session has its own requestAnimationFrame method separate from that of the window
-        //  https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/213#issuecomment-947943386)
-        this.tilesRenderer.downloadQueue.schedulingCallback = this.tilesSchedulingCB;
-        this.tilesRenderer.parseQueue.schedulingCallback = this.tilesSchedulingCB;
+
+        // Store the original scheduling callback for this layer
+        this._originalSchedulingCallback = this.tilesSchedulingCB;
```
Comment (Desplandis) [inline packages/Main/src/Layer/OGC3DTilesLayer.js]: Do we need to create another variable, we do not reassign `tilesSchedulingCB`?

File: packages/Main/src/Layer/OGC3DTilesLayer.js [hunk 7]
```diff
@@ -335,20 +333,58 @@ class OGC3DTilesLayer extends GeometryLayer {
...
                 parseQueue: this.tilesRenderer.parseQueue,
+                layerCallbacks: [this._originalSchedulingCallback],
             };
             view.addEventListener(VIEW_EVENTS.DISPOSED, (evt) => {
                 delete viewers[evt.target.id];
             });
         }
+
+        // Store the view reference for cleanup
+        this._viewId = id;
```
Comment (Desplandis) [inline packages/Main/src/Layer/OGC3DTilesLayer.js:373]: So we can't use a 3DTiles layers in more than one view?

File: packages/Main/src/Layer/OGC3DTilesLayer.js [hunk 8]
```diff
@@ -470,7 +506,24 @@ class OGC3DTilesLayer extends GeometryLayer {
      * Deletes the layer and frees associated memory
      */
     delete() {
```
Comment (Desplandis) [inline packages/Main/src/Layer/OGC3DTilesLayer.js:494]: I just looked at the code of `View#removeLayer` and we actually call the `Layer#delete` method and there is no method in `Layer` to actually just delete view-related stuff... So if you remove a layer from a view, you kind of remove it from all views... No way to share layers between views...  @jailln I will open a proposal to kind of document/formalize the current layer lifecycle and propose a better mechanism.

File: packages/Main/src/Layer/OGC3DTilesLayer.js [hunk 9]
```diff
@@ -335,20 +333,58 @@ class OGC3DTilesLayer extends GeometryLayer {
...
         } else {
+            // Set the combined callback (cf. above comment)
+            this.tilesRenderer.downloadQueue.schedulingCallback = this.tilesSchedulingCB;
+            this.tilesRenderer.parseQueue.schedulingCallback = this.tilesSchedulingCB;
+
             viewers[id] = {
                 lruCache: this.tilesRenderer.lruCache,
                 downloadQueue: this.tilesRenderer.downloadQueue,
                 parseQueue: this.tilesRenderer.parseQueue,
+                layerCallbacks: [this._originalSchedulingCallback],
```
Comment (Desplandis) [inline packages/Main/src/Layer/OGC3DTilesLayer.js]: IMHO, you should use a map from layer ids to callbacks (or an object). It should simplify the code as you will not have to null-check.

I think of something like:

```suggestion
                layerCallbacks: {
                   [this.id]: this._originalSchedulingCallback,
                },
```

File: packages/Main/src/Layer/OGC3DTilesLayer.js [hunk 10]
```diff
@@ -470,7 +506,24 @@ class OGC3DTilesLayer extends GeometryLayer {
...
+        // Clean up the callback reference from the shared callbacks
+        if (this._viewId !== null && viewers[this._viewId] && viewers[this._viewId].layerCallbacks) {
+            const callbackIndex = viewers[this._viewId].layerCallbacks.indexOf(this._originalSchedulingCallback);
+            if (callbackIndex !== -1) {
+                viewers[this._viewId].layerCallbacks.splice(callbackIndex, 1);
+            }
+            // If no more layers are using this view's queues, clean up completely
+            if (viewers[this._viewId].layerCallbacks.length === 0) {
+                delete viewers[this._viewId];
+            }
```
Comment (Desplandis) [inline packages/Main/src/Layer/OGC3DTilesLayer.js]: If you use a map-like structure this should greatly simplify this code.

**Review by Desplandis — COMMENTED** [review]
I have a few comments on your PR. Mainly related to the use of a map-like structure to keep track of callbacks and not reassigning the tilesRenderer callback every time we add a layer. IMO this could greatly reduce the complexity of the code.

File: packages/Main/src/Layer/OGC3DTilesLayer.js (hunk 7 above)
Comment (AnthonyGlt) [reply packages/Main/src/Layer/OGC3DTilesLayer.js:373]: As you noticed below, this case isn't not currently well handled in iTowns. The layer is dependent of the view

**Review by Desplandis — APPROVED** [review]

**Comment by AnthonyGlt** [comment]
no regression in vr :+1:
