### PR TITLE
Fix helper 3dtiles

### LINKED ISSUE #989: 3DTiles bounding boxes debug tool erroneous display
## Your Environment
 * Version used: V2.6.0 (git tag), [98abec9d](https://github.com/iTowns/itowns/commit/98abec9da9e7e5809c70b49ad2ffc35875c83989) (technically we use [this fork](https://github.com/jailln/itowns/tree/planar_3dtiles) as WIP) 
 * Browser Name and version: Firefox 64.0
 * Operating System and version (desktop or mobile): macOS 10.13.6
 * Link to your project: [this WIP fork](https://github.com/jailln/itowns/tree/planar_3dtiles) of the official iTowns

## Context
Gltf and 3D-Tiles made different choices for their referential systems ([gltf is Y-Up while 3DTiles is Z-up](https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/280)). 
Previous versions of 3D-Tiles specifications allowed to deal with this discrepancy by enabling the usage of an [`asset.gltfUpAxis` attribute](https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/175).
But the current version of 3D-Tiles specification (that [uses gltf version 2 as base for its B3dm's](https://github.com/AnalyticalGraphicsInc/3d-tiles/blob/master/specification/TileFormats/Batched3DModel/README.md#binary-gltf)) dropped this `asset.gltfUpAxis` feature as mentionned by [ lilleyse comment dated May 10, 2018](https://github.com/AnalyticalGraphicsInc/3d-tiles/issues/280).
When working with source data that is inherently z-up, the current [3D-Tiles manner of dealing with the gltf/3DTiles axis discrepancy](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#gltf-transforms) recommends the following common workflow:
```
   - Mesh data, including positions and normals, are not modified - they remain z-up.
   - The root node matrix specifies a column-major z-up to y-up transform. This transforms the source data into a y-up coordinate system as required by glTF.
   - At runtime the glTF is transformed back from y-up to z-up with the matrix above. Effectively the transforms cancel out.
```
where the considered `root node matrix` is the gltf one (as opposed to the [tile-set's root](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#tileset) tile [transform matrix](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#tile-transforms)).

Now when setting up, checking or adjusting, the spatial placement of some geographical data set **being able to display its bounding** often proves to be a really useful debugging tool.  
Remember that the definition of a [`tile.boundingVolume` (e.g. a Box)](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#boundingvolumebox), associated e.g. to such 'inherently z-up data',  is done at the Tile level and that its positioning is constrained to use a [Tile Transform matrix](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/specification#transforms) (as opposed to the gltf's `root node matrix` of the data of which it is a bounding volume).

Is important to note that the above remark implies that a `tile.boundingVolume` is *not* related to the above mentioned historical `asset.gltfUpAxis` (because a Bounding Volume is not expressed at the gltf level). This fact seems in apparent contradiction with the iTowns' [code that displays BoudingVolumes](https://github.com/iTowns/itowns/blob/master/utils/debug/3dTilesDebug.js#L74).

Anyhow, iTowns' current [code for parsing B3dm](https://github.com/iTowns/itowns/blob/master/src/Parser/B3dmParser.js#L119) offers to support the now deprecated 3D-tiles' `asset.gltfUpAxis` trick-feature. And although this feature support should simply be deprecated, this code is still coherent with the current 3D-Tiles specification in that it allows to properly display old (using `asset.gltfUpAxis`) as well as new Tilesets . (Please note that when deprecating this code the `gltf.scene.applyMatrix(matrixChangeUpVectorZtoY);` will have to be kept, in order to properly handle the gltf vs 3DTiles axis discrepancy). 

In opposition, and in order for Bounding Volumes (and bounding boxes) of new tile-sets (i.e. tile-sets that are 3D-Tiles current specification compliant) to be properly displayed, the corresponding iTown's code seems to require some adaptation. Indeed the [Bounding Volume (debug) *display* code](https://github.com/iTowns/itowns/blob/master/utils/debug/3dTilesDebug.js#L74) mirrors its [B3dm parsing counterpart](https://github.com/iTowns/itowns/blob/master/src/Parser/B3dmParser.js#L119) and *realizes a (default) Y to Z rotation when it should NOT*.

The undesired effect (bug?) is that the displayed bounding boxes appear erroneously rotated by 90 degrees as (not so well) shown on the following illustration  appear erroneously rotated by 90 degrees

## Steps to Reproduce (for bugs)
Because we are currently working on a feature evolution of the [Py3Dtiles toolkit](https://github.com/Oslandia/py3dtiles) (WIP is on [this fork](https://github.com/MEPP-team/py3dtiles/tree/Tiler)) and its iTowns client side counterpart is also [on a fork/branch](https://github.com/jailln/itowns/tree/planar_3dtiles) providing such steps might be a little lengthy for the time being. But if providing those steps happened to be mandatory for this issue to be resolved then we shall of course comply with the demand (read we need it bad ;)

## Expected Behavior
Bounding Volume of contemporary tilesets should be properly displayed (without an erroneous rotation).

## Actual Behavior
The displayed bounding boxes  appear erroneously rotated by 90 degrees ha (not so well) shown on the following illustration  appear erroneously rotated by 90 degrees

## Possible Cause/Fix/Solution
Fixing this issue (while still allowing the display of "old" tilesets) will require to programmatically distinguish between:
 - "old" tile sets using `asset.gltfUpAxis` trick-feature
 - "new" tile sets not using this feature

A (not that clean) way of doing so might be to use make the following "heuristic" (assumption):
 - Tile sets using `asset.gltfUpAxis` trick-feature are old ones
 - Tile sets NOT using `asset.gltfUpAxis` trick-feature AND [using gltf version 2](https://github.com/iTowns/itowns/blob/master/src/Parser/B3dmParser.js#L161)  are "new" ones.

### LINKED ISSUE #1316: BBox missing in 3dtiles debugging
In the two 3dtiles examples, when checking `boudingbox` in the debug interface, nothing appears on the screen. This has been broken since 7b067c7d

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description
* fix calling update 3dtile helper.
* fix bbox 3dtile transformation.

fix #1316
fix #989

bbox1
bbox2

### CODE REVIEW

File: utils/debug/3dTilesDebug.js [hunk 1]
```diff
@@ -38,17 +37,13 @@ export default function create3dTilesDebugUI(datDebugTool, view, _3dTileslayer)
...
-                if (metadata.boundingVolume.box) {
-                    metadata.boundingVolume.box.getSize(size);
-                    const g = new THREE.BoxGeometry(size.x, size.y, size.z);
-                    const material = new THREE.MeshBasicMaterial({ wireframe: true });
-                    helper = new THREE.Mesh(g, material);
-                    metadata.boundingVolume.box.getCenter(helper.position);
-                }
+                } else if (metadata.boundingVolume.box) {
+                    bboxMesh.geometry.boundingBox = metadata.boundingVolume.box;
+                    helper = new THREE.BoxHelper(bboxMesh);
```
Comment (zarov) [inline utils/debug/3dTilesDebug.js:43]: Note: this could be used in `OBBHelper`.

**Review by zarov — COMMENTED** [review]
LGTM, waiting for the validation of #989

File: utils/debug/3dTilesDebug.js (hunk 1 above)
Comment (gchoqueux) [reply utils/debug/3dTilesDebug.js:43]: yes

**Review by zarov — APPROVED** [review]
