### PR TITLE
fix (Depth) : correct calculation of depth

### LINKED ISSUE #411: White screen when zooming
When the globe is ready and you zoom with the scroll wheel, everything suddenly disappears when your close to level 13 (like we were under the globe) and all we can see is a white screen.
The same thing happens when using the `globeView.controls.setZoom()` for levels higher than 9. (same bahavior for `setScale()`, `setRange()` and `setOrbitalPosition()`, which is logical).

It seems that this bug appeared in the following commit https://github.com/iTowns/itowns/commit/6c7d9b6b54c1a06116f5b0962511224385591bc3

### PR DESCRIPTION
**Pull request by gchoqueux**
## Description

Use of depth buffers instead of calculating Z in the shader TileFS.glsl
this PR doesn't resolve #411 
## Motivation and Context

Before `DEPTH_MODE` returns Z value between 0 and camera.far, as `packDepthToRGBA` packs values between 0.0 and 1.0, Z was divided by a big constant.
It is therefore more logical to use the depth (between 0.0 and 1.0) and convert it out of the shader

### CODE REVIEW

**Comment by peppsac** [comment]
`screenCoordsToNodeId` uses the `factor` argument so this change will break it.

**Comment by gchoqueux** [comment]
@peppsac updated

File: src/Core/Prefab/GlobeView.js [hunk 1]
```diff
@@ -427,13 +428,25 @@ GlobeView.prototype.getPickingPositionFromDepth = function getPickingPositionFro
     direction.applyMatrix4(matrix);
     direction.sub(ray.origin);
 
-    var angle = direction.angleTo(ray.direction);
+    const angle = direction.angleTo(ray.direction);
 
     depthRGBA.fromArray(buffer).divideScalar(255.0);
 
-    var depth = unpack1K(depthRGBA, 100000000.0) / Math.cos(angle);
+    let orthoZ = 0;
```
Comment (peppsac) [inline src/Core/Prefab/GlobeView.js]: Maybe you could move this function to `c3DEngine`, something like: `c3DEngine.depthBufferValueToZ(depthRGBA)`?

Comment (gchoqueux) [reply src/Core/Prefab/GlobeView.js]: done

**Review by peppsac — APPROVED** [review]
