### PR TITLE
Fix ElevationLayer removal

### LINKED ISSUE #2221: [Bug - ElevationLayer]  Issues caused by the removal of an ElevationLayer
When we remove an ElevationLayer, the map bugs, tiles has faulty loading and may crash the browser

## Your Environment
Master Branch

## Context
On this video, I've implemented 2 buttons to use on the view_25d_map example
"Terrain IN" does  `view.addLayer(wmsElevationLayer);`
"Terrain OUT" does  `view.removeLayer('wms_elevation');`

[Screencast from 06-11-2023 16:21:03.webm](https://github.com/iTowns/itowns/assets/126568810/324f6d1e-a27c-4b2a-b059-adf363b06f56)

You can notice that the behavior is not the same before adding the terrain and after removing it. It should be the same

I tried it on the globe using view_3d_map example. The terrain is already added at the beginning, I juste remove it using the button, which does 
```
//ids => list of the elevation layers ids
for (id of ids) {
 view.removeLayer(id);
}
```
[Screencast from 06-11-2023 16:36:26.webm](https://github.com/iTowns/itowns/assets/126568810/ad55751f-8853-4869-b869-b61b42a4f8d6)

Same weird behavior and a huge decrease in performances.
I've tried with the cache boolean `view.removeLayer(id, cacheBoolHere);`, the behavior differs but no improvement.

## Expected Behavior
I expect when deleting the elevationlayer to have the same behavior as if the elevationlayer was never added

### PR DESCRIPTION
**Pull request by jailln**
## Description
`node.material.elevationLayerIds[layerId]` is removed by `node.material.removeLayer(layerId);` so the bbox min and max elevation values were never reset which caused visual artifacts when removing an `ElevationLayer` from the view.

You can use the following example to test the fix: https://gist.github.com/jailln/90c67187a0c8e4e94eb8ea5ac3cc92a0
 
Note that bbox min and max z values should not be reset to 0 but to the min and max of the remaining `ElevationLayers` attached to this `TileMesh`. This is another bug that also implies other changes in this bbox min and max elevation values management so I opened #2282 instead of fixing it now. (also note that the proposed implementation somehow doesn't seem to break anything if there are multiple `ElevationLayer` in the view and one is removed).

## Motivation and Context

Closes #2221

### CODE REVIEW

File: src/Process/LayeredMaterialNodeProcessing.js [hunk 1]
```diff
@@ -238,10 +238,10 @@ export function updateLayeredMaterialNodeElevation(context, layer, node, parent)
 export function removeLayeredMaterialNodeLayer(layerId) {
     return function removeLayeredMaterialNodeLayer(node) {
```
Comment (Desplandis) [inline src/Process/LayeredMaterialNodeProcessing.js:242]:
```suggestion
    /**
     * @param {TileMesh} node - The node to udpate.
     */
    return function removeLayeredMaterialNodeLayer(node) {
```

**Review by Desplandis — APPROVED** [review]
Okay for me!
Fixes the announced bug!
