### PR TITLE
3D Tiles fixes and perf improvements

### LINKED ISSUE #1859: Unstable 3d tiles rendering in itowns
When I zoom or pan some tiles just not render or whole tileset destructs until the view angle or zoom will not be changed.

## Your Environment
- itowns version used: 2.38.1
- b3dm tiles
- link to json: hided

## Context
Here is videos to see the behavior:
1. https://youtu.be/ei3bzoLoTrs
2. https://youtu.be/EzqhBOsuaBs
3. https://youtu.be/XywzT3f29ps

I've tried:
- to set the sseThreshold = 0.3 and 100
- tileset.geometricError = 1 and 100 and other values
But these options don't solve the issue.

## Steps to Reproduce (for bugs)
```
const tiles3dLayer = new itowns.C3DTilesLayer(datasetTilesSet3dObject.id, {
    name: datasetTilesSet3dObject.name,
    source: new itowns.C3DTilesSource({
      url: datasetTilesSet3dObject.url,
    }),
    sseThreshold: 1,
}, this.itownsViewer)
itowns.View.prototype.addLayer.call(this.itownsViewer, tiles3dLayer)
```

## Expected Behavior
I expect that all tiles in camera focus will be rendered no matter the zoom or view angle.
This issue and the [previous](https://github.com/iTowns/itowns/issues/1853) are critical for us and if there is no solution for them we'll have to avoid the itowns in our projects.

### LINKED ISSUE #1888: 3D Tiles debug tools: bounding spheres are not displayed
## Your Environment
* Version used: 2.38.2
* Browser Name and version: Firefox and Chrome
* Operating System and version (desktop or mobile): Linux

## Context

3D Tiles debug tools "bounding box" checkbox does not work for 3D Tiles tilesets with bounding spheres. There is no error in the console. It is limiting for debugging such tilesets.

## Steps to Reproduce (for bugs)
1. Create an example with a 3D Tiles tileset with bounding spheres (e.g. https://storage.yandexcloud.net/gis-3d-models/data/tiles3d/Valaam_Aerial_Survey/Scene/Cesium.json from #1859) and with a 3D Tiles debug UI (e.g. `debug.create3dTilesDebugUI(menuGlobe.gui, view, tileset, d);`)
2. Zoom to the tileset. Camera position for the above-mentioned tileset:
```
        var placement = {
            coord: new itowns.Coordinates('EPSG:4326', 30.950135, 61.395949, 0),
            range: 3000,
            tilt: 22,
        }
```
4. Check the "Bounding box" checkbox

## Expected Behavior
Bounding spheres should be displayed (the code exists but I don't know if it ever worked ?).

## Actual Behavior
Nothing is displayed.

### PR DESCRIPTION
**Pull request by jailln**
Some 3D tiles fixes:
* Fix a bug that impacted display of 3D tiles with sphere bounding volumes, closes #1859
* Fix display of 3D Tiles bounding volumes of type sphere, closes #1888 and #1853

Perf improvement:
* Improve perfs for 3D tiles with bounding region by converting bounding regions to bounding spheres. Previously, bounding regions where converted to [OBB](https://github.com/iTowns/itowns/blob/master/src/Renderer/OBB.js) and the AABB englobing the OBB was used for culling and SSE computation. Now, they are converted to bounding spheres and the sphere is used for culling and SSE computation. Depending on the cases it can be a bigger approximation than before but it is faster and I didn't see any visual discrepencies. I tested the perf differences on a 3D Tiles photogrammetry tileset (~500Go, 13732 tiles with only bounding regions) that I cannot share unfortunately. On the master, we spend most of our time initializing the bounding region:

before-PR-0

before-PR-1

After the PR, we spend most of the time in parsing and preparing for rendering:

after-PR-0
after-PR-1

I also tried to implement a conversion to [threejs' OBB](https://threejs.org/docs/index.html?q=obb#examples/en/math/OBB) and to implement a culling algorithm on OBB (SSE computation for OBB is easy) but didn't succeed completely (can be seen on [the following branch](https://github.com/jailln/itowns/tree/fix/GEO-18291-3dtiles-mel-history-save)). Another way would have been to [improve OBB.setFromExtent](https://github.com/jailln/itowns/blob/fix/GEO-18291-3dtiles-mel-history-save/src/Renderer/OBB.js#L106) which is the culprit but I haven't found another way of implementing it yet. Propositions are welcome :)

BREAKING CHANGE: Remove region, box and sphere properties of C3DTBoundingVolume. They have been replaced by volume property which contains a THREE.Box3 (for box) or a THREE.Sphere (for sphere or region). Initial bounding volume type can be retrieved with the initialVolumeType property.

### CODE REVIEW

File: src/Core/3DTiles/C3DTBoundingVolume.js [hunk 1]
```diff
@@ -1,27 +1,103 @@
...
+
+// Culling scratch value
 const worldCoordinateCenter = new THREE.Vector3();
 
+//
+/**
+ * Bounding region is converted to a bounding sphere to simplify and speed computation and culling. This function
+ * computes a sphere enclosing the bounding region.
+ * @param {Object} region - the parsed json from the tile representing the region
+ * @param {THREE.Matrix4} inverseTileTransform - the inverse transformation matrix of the tile to transform the produced
```
Comment (valentinMachado) [inline src/Core/3DTiles/C3DTBoundingVolume.js]: If the parameter passed is a matrix4, IMO tileMatrixWorldInverse/tileMatrixInverse is a better name (and fit more THREE way of naming variables)

File: src/Core/3DTiles/C3DTBoundingVolume.js [hunk 2]
```diff
@@ -1,27 +1,103 @@
...
+import { C3DTilesTypes, C3DTilesBoundingVolumeTypes } from './C3DTilesEnums';
+
+const ellipsoid = new Ellipsoid();
+
+// bounding box scratch variables
+const boxSize = new THREE.Vector3();
+const boxCenter = new THREE.Vector3();
+
+// Bounding region scratch variables
+const southEastUpCarto = new Coordinates('EPSG:4326');
```
Comment (valentinMachado) [inline src/Core/3DTiles/C3DTBoundingVolume.js:13]: I am not sure but according this [specification](https://docs.ogc.org/cs/18-053r2/18-053r2.html#32) crs of the bouding region is [EPSG 4979](http://spatialreference.org/ref/epsg/4979/) and not EPSG:4326

File: src/Core/3DTiles/C3DTBoundingVolume.js [hunk 3]
```diff
@@ -1,27 +1,103 @@
...
+    const northDeg = THREE.MathUtils.radToDeg(north);
+
+    northWestBottomCarto.setFromValues(westDeg, northDeg, minHeight);
+    ellipsoid.cartographicToCartesian(northWestBottomCarto, northWestBottomVec3);
+
+    southEastUpCarto.setFromValues(eastDeg, southDeg, maxHeight);
+    ellipsoid.cartographicToCartesian(southEastUpCarto, southEastUpVec3);
+
+    const regionCenter = new THREE.Vector3();
+    regionCenter.addVectors(northWestBottomVec3, southEastUpVec3).divideScalar(2);
```
Comment (valentinMachado) [inline src/Core/3DTiles/C3DTBoundingVolume.js]: prefer a [lerp](https://threejs.org/docs/?q=vector#api/en/math/Vector3.lerp)

File: src/Core/3DTiles/C3DTBoundingVolume.js [hunk 4]
```diff
@@ -1,27 +1,103 @@
...
+ * @param {Object} box - the parsed json from the tile representing the box
+ * @return {THREE.Box3} the bounding box of the tile
+ */
+function initFromBox(box) {
+    // box[0], box[1], box[2] = center of the box
+    // box[3], box[4], box[5] = x axis direction and half-length
+    // box[6], box[7], box[8] = y axis direction and half-length
+    // box[9], box[10], box[11] = z axis direction and half-length
+    boxCenter.set(box[0], box[1], box[2]);
+    boxSize.set(box[3], box[7], box[11]).multiplyScalar(2);
```
Comment (valentinMachado) [inline src/Core/3DTiles/C3DTBoundingVolume.js:70]: you don't take into acount box[4/5/6/8/9/10] assuming that the box is XY aligned, is that the behavior expected ?

File: src/Core/3DTiles/C3DTBoundingVolume.js [hunk 5]
```diff
@@ -1,27 +1,103 @@
...
  * (i.e. for which 3D Tiles class) the parsing of the extension should be done.
- * @property {THREE.Box3} box - Bounding box, defined only if the Bounding Volume
- * is a box.
- * @property {OBB} region - Bounding region, defined only if the Bounding
- * Volume is a region.
- * @property {THREE.Sphere} sphere - Bounding sphere, defined only if the
- * Bounding Volume is a sphere.
+ * @property {String} initialVolumeType - the initial volume type to be able to dissociate spheres
+ * and regions if needed since both are converted to spheres (one of {@link C3DTilesBoundingVolumeTypes})
+ * @property {THREE.Box3|THREE.Sphere} volume - The 3D bounding volume created. Can be a THREE.Box3 for bounding volumes
```
Comment (valentinMachado) [inline src/Core/3DTiles/C3DTBoundingVolume.js:98]: I think it's a poor pattern to store in a single variable different type of object (`volume`) then to use another variable (here `initialVolumeType`) to know how to manipulate `volume`.. (btw you could use [instanceof](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators/instanceof) instead of initialVolumeType)

you could create a wrapper abstract class called `Volume` implementing a method `isVisible(camera, tileMatrixWorld)` then specifying `SphereVolume` and `BoxVolume` (class extending `Volume`) the specific behavior.

you could also put two attributes in `C3DTBoundingVolume` instead of `volume` one called `box` and the other one `sphere` which is the solution I rather, since a `C3DTBoundingVolume` could have the both and it avoids to create an abstract class

File: src/Core/3DTiles/C3DTBoundingVolume.js [hunk 6]
```diff
@@ -47,71 +126,44 @@ class C3DTBoundingVolume {
...
+     * @returns {boolean} true if the camera is outside the viewer request volume, false otherwise.
+     */
     viewerRequestVolumeCulling(camera, tileMatrixWorld) {
-        if (this.region) {
+        if (this.initialVolumeType === C3DTilesBoundingVolumeTypes.region) {
             console.warn('Region viewerRequestVolume not yet supported');
             return true;
         }
-        if (this.box) {
+        if (this.initialVolumeType === C3DTilesBoundingVolumeTypes.box) {
```
Comment (valentinMachado) [inline src/Core/3DTiles/C3DTBoundingVolume.js:156]: why box is not supported here and is above (constructor and `boudingVolumeCulling`) ?

File: src/Core/3DTiles/C3DTBoundingVolume.js [hunk 7]
```diff
@@ -47,71 +126,44 @@ class C3DTBoundingVolume {
...
         }
-        if (this.sphere) {
-            worldCoordinateCenter.copy(this.sphere.center);
+        if (this.initialVolumeType === C3DTilesBoundingVolumeTypes.sphere) {
+            worldCoordinateCenter.copy(this.volume.center);
             worldCoordinateCenter.applyMatrix4(tileMatrixWorld);
             // To check the distance between the center sphere and the camera
             if (!(camera.camera3D.position.distanceTo(worldCoordinateCenter) <=
-                this.sphere.radius)) {
+                this.volume.radius)) {
```
Comment (valentinMachado) [inline src/Core/3DTiles/C3DTBoundingVolume.js]: you could write return the condition of the if

File: src/Core/3DTiles/C3DTileset.js [hunk 8]
```diff
@@ -1,7 +1,11 @@
 import * as THREE from 'three';
 import C3DTBoundingVolume from './C3DTBoundingVolume';
-import C3DTilesTypes from './C3DTilesTypes';
+import { C3DTilesTypes } from './C3DTilesEnums';
 
+// Inverse transform of a tile, computed from the tile transform and used when parsing the bounding volume of a tile
```
Comment (valentinMachado) [inline src/Core/3DTiles/C3DTileset.js:5]: Same as above, sometime you use matrix and sometime transform.. I guess transform is the term used in 3DTiles specs and the other in THREE. I think one should be picked in order to harmonize code, I rather matrix because I think is better to be aligned with THREE

File: src/Core/3DTiles/C3DTileset.js [hunk 9]
```diff
@@ -85,12 +89,9 @@ class C3DTileset {
         }
 
         tile.viewerRequestVolume = tile.viewerRequestVolume ?
-            new C3DTBoundingVolume(tile.viewerRequestVolume,
-                inverseTileTransform,
-                registeredExtensions) : undefined;
+            new C3DTBoundingVolume(tile.viewerRequestVolume, inverseTileTransform, registeredExtensions) : undefined;
```
Comment (valentinMachado) [inline src/Core/3DTiles/C3DTileset.js]: Prefer setting the variable to `null` instead of `undefined` to make the difference between something which is meant to be read with something just not defined

[check also](https://stackoverflow.com/questions/6604749/what-reason-is-there-to-use-null-instead-of-undefined-in-javascript)

**Review by valentinMachado — COMMENTED** [review]
This review does not treat the solution implemented (replacing C3DTBoundingVolume by sphere) and if this is actually working.. but is more about the code in itself.

What could I do to check if the solution is working ?

File: src/Core/3DTiles/C3DTBoundingVolume.js [hunk 10]
```diff
@@ -1,27 +1,103 @@
...
+const southEastUpCarto = new Coordinates('EPSG:4326');
+const southEastUpVec3 = new THREE.Vector3();
+const northWestBottomCarto = new Coordinates('EPSG:4326');
+const northWestBottomVec3 = new THREE.Vector3();
+const radiusScratch = new THREE.Vector3();
+
+// Culling scratch value
 const worldCoordinateCenter = new THREE.Vector3();
 
+//
```
Comment (mgermerie) [inline src/Core/3DTiles/C3DTBoundingVolume.js]: Could you remove the empty comment ?

**Comment by jailln** [comment]
Hi @valentinMachado , thanks for your review and sorry for the late response. 

> What could I do to check if the solution is working ?

You can use a 3D Tiles dataset with bounding volumes of region type to test if it works. The only open source one and available online that I know is [this one](https://github.com/CesiumGS/3d-tiles-samples/tree/main/1.0/TilesetWithRequestVolume).

File: src/Core/3DTiles/C3DTBoundingVolume.js (hunk 2 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTBoundingVolume.js:13]: Yes. However, EPSG:4979 is the 3D extension of EPSG:4326 (same x,y axes and with a z altitude in meters). Using EPSG:4979 would be clearer but we confuse these two crs in itowns (see #1926)

File: src/Core/3DTiles/C3DTBoundingVolume.js (hunk 4 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTBoundingVolume.js:70]: It is a bug, 3D tiles bounding boxes are OBB and not AABB but they are interpreted as AABB. I decided to not treat it in this PR. See #2126

File: src/Core/3DTiles/C3DTBoundingVolume.js (hunk 5 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTBoundingVolume.js:98]: The last pattern was the previously used pattern. However, if we choose this one I would keep the `initialVolumeType` to be able to know if the sphere comes from a bounding sphere or from a bounding region, in case it may be useful for itowns' users in some way. The second pattern is also interesting, I actually thought about it when implementing this. I don't have time to implement it right now but I'll come back to it soon.

File: src/Core/3DTiles/C3DTBoundingVolume.js (hunk 6 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTBoundingVolume.js:156]: Just because it has never been implemented but it could indeed easily be supported. Same for regions. I just decided not to do it in this PR

File: src/Core/3DTiles/C3DTileset.js (hunk 9 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTileset.js]: absolutely

File: src/Core/3DTiles/C3DTileset.js (hunk 8 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTileset.js:5]: ok, I picked matrix

File: src/Core/3DTiles/C3DTBoundingVolume.js (hunk 7 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTBoundingVolume.js]: yes, done

File: src/Core/3DTiles/C3DTBoundingVolume.js (hunk 3 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTBoundingVolume.js]: ok, done

File: src/Core/3DTiles/C3DTBoundingVolume.js (hunk 1 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTBoundingVolume.js]: Yep you're right, done

File: src/Core/3DTiles/C3DTBoundingVolume.js [hunk 11]
```diff
@@ -1,44 +1,123 @@
...
+    return box3;
+}
+
+/**
+ * Creats a bounding sphere from a json describing a sphere in a 3D Tiles tile.
+ * @param {Object} sphere - the parsed json from the tile representing the sphere
+ * @returns {THREE.Sphere} the bounding sphere of the tile
+ */
+function initFromSphere(sphere) {
+    const sphereCenter = new THREE.Vector3();
```
Comment (mgermerie) [inline src/Core/3DTiles/C3DTBoundingVolume.js:82]: Why not keeping a "global" constant for `sphereCenter` (like `boxCenter`) ?

File: src/Core/3DTiles/C3DTBoundingVolume.js [hunk 12]
```diff
@@ -1,44 +1,123 @@
...
+    const southDeg = THREE.MathUtils.radToDeg(south);
+    const northDeg = THREE.MathUtils.radToDeg(north);
+
+    northWestBottomCarto.setFromValues(westDeg, northDeg, minHeight);
+    ellipsoid.cartographicToCartesian(northWestBottomCarto, northWestBottomVec3);
+
+    southEastUpCarto.setFromValues(eastDeg, southDeg, maxHeight);
+    ellipsoid.cartographicToCartesian(southEastUpCarto, southEastUpVec3);
+
+    const regionCenter = new THREE.Vector3();
```
Comment (mgermerie) [inline src/Core/3DTiles/C3DTBoundingVolume.js:49]: Could you instantiate `regionCenter` outside of the method ? I believe instancing new objects like `THREE.Vector3()` repeatedly can cause performance drops with garbage collector.  I think it is better to avoid it if possible.

File: src/Core/3DTiles/C3DTBoundingVolume.js (hunk 6 above)
Comment (mgermerie) [reply src/Core/3DTiles/C3DTBoundingVolume.js:156]: Could you please open an issue about it ?

File: src/Process/3dTilesProcessing.js [hunk 13]
```diff
@@ -265,9 +234,6 @@ export function init3dTilesLayer(view, scheduler, layer, rootTile) {
             tile.updateMatrixWorld();
             layer.tileset.tiles[tile.tileId].loaded = true;
             layer.root = tile;
-            // The extent is calculated but it's never used in 3D tiles process
-            layer.extent = boundingVolumeToExtent(layer.crs || view.referenceCrs,
-                tile.boundingVolume, tile.matrixWorld);
```
Comment (mgermerie) [inline src/Process/3dTilesProcessing.js:270]: Do you have an idea why the extent was calculated in the first place ?

File: utils/debug/3dTilesDebug.js
Comment (mgermerie) [inline utils/debug/3dTilesDebug.js:1]: Perhaps it would be interesting to display bounding region here. We could compute the OBB for bounding regions the way it was done in `C3DTilesBoundingVolume` but only in debug tools ?

I wonder if we rather display debug information that represents the original 3dtiles data (bounding regions) or information relative to what is seen and used for computing (bounding spheres). WDYT is more interesting for users @jailln and @Desplandis ?

File: src/Core/3DTiles/C3DTBoundingVolume.js (hunk 10 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTBoundingVolume.js]: ok, done

File: src/Core/3DTiles/C3DTBoundingVolume.js (hunk 11 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTBoundingVolume.js:82]: this was the cause of #1853 and #1888 : the same `Vector3` instance was used for all spehres bounding boxes and the center is not cloned in [Sphere constructor](https://github.com/mrdoob/three.js/blob/master/src/math/Sphere.js#L12).
For box it's ok to use the same `boxCenter` and `boxSize` instance since they are used in `setFromCenterAndSize` which are not stored directly in the box.

File: src/Core/3DTiles/C3DTBoundingVolume.js (hunk 12 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTBoundingVolume.js:49]: No for the same reason than for the sphere bounding volumes center

File: src/Process/3dTilesProcessing.js (hunk 13 above)
Comment (jailln) [reply src/Process/3dTilesProcessing.js:270]: no idea

File: utils/debug/3dTilesDebug.js
Comment (jailln) [reply utils/debug/3dTilesDebug.js:1]: In my opinion it is better to display what we use to perform the culling (i.e. bounding spheres now)

File: src/Core/3DTiles/C3DTBoundingVolume.js (hunk 6 above)
Comment (jailln) [reply src/Core/3DTiles/C3DTBoundingVolume.js:156]: done [2216](https://github.com/iTowns/itowns/issues/2216)

File: utils/debug/3dTilesDebug.js
Comment (Desplandis) [reply utils/debug/3dTilesDebug.js:1]: @jailln @mgermerie I also think this is better to display what shape the engine actually uses to perform bounds checking. At least, it may not create confusion to the end-user about the culling behavior.

File: src/Core/3DTiles/C3DTBoundingVolume.js (hunk 11 above)
Comment (mgermerie) [reply src/Core/3DTiles/C3DTBoundingVolume.js:82]: Ok I see. Thanks for the explanation.

File: src/Process/3dTilesProcessing.js (hunk 13 above)
Comment (mgermerie) [reply src/Process/3dTilesProcessing.js:270]: @gchoqueux maybe you know some history behind this ?

**Review by mgermerie — APPROVED** [review]

**Comment by mgermerie** [comment]
Except from the conflict that should be easy to fix it's all good for me. Thanks !
