### PR TITLE
fix(terrain): fix depth & transparency issues

### LINKED ISSUE #2561: [REGRESSION] We can't change the opacity of the globe
Since https://github.com/iTowns/itowns/pull/2374/files#diff-2cbabdb42b34b51f54a3ad1eabf469e8990ea4073b43780ff5f2cc6709e08847

It seems that we can't edit the opactiy of the globe anymore

## Steps to Reproduce

1. Use the following example code
2. Click on the button "Change Tile Layer Opacity"

## Expected Behavior

Image

## Actual Behavior

Image

```html

<html>
<head>
    <title>Itowns - Globe</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="css/example.css">
    <link rel="stylesheet" type="text/css" href="css/LoadingScreen.css">
    <link rel="stylesheet" type="text/css" href="css/widgets.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/dat-gui/0.7.6/dat.gui.min.js"></script>
    <style>
        #removeElevationBtn {
            position: absolute;
            top: 10px;
            left: 10px;
            z-index: 1000;
            padding: 10px 15px;
            background-color: #ff6b6b;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
        }
        #removeElevationBtn:hover {
            background-color: #ff5252;
        }
        #removeElevationBtn:disabled {
            background-color: #cccccc;
            cursor: not-allowed;
        }
        #opacityBtn {
            position: absolute;
            top: 60px;
            left: 10px;
            z-index: 1000;
            padding: 10px 15px;
            background-color: #4caf50;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 14px;
        }
        #opacityBtn:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>
<div id="viewerDiv"></div>
<button id="removeElevationBtn" onclick="removeElevationLayer()">Remove Elevation Layer</button>
<button id="opacityBtn" onclick="changeTileLayerOpacity()">Change Tile Layer Opacity</button>

<!-- Import iTowns source code -->
<script src="../dist/itowns.js"></script>
<script src="../dist/debug.js"></script>
<!-- Import iTowns Widgets plugin -->
<script src="../dist/itowns_widgets.js"></script>
<!-- Import iTowns LoadingScreen and GuiTools plugins -->
<script src="js/GUI/GuiTools.js"></script>
<script src="js/GUI/LoadingScreen.js"></script>

<script type="text/javascript">

    // ---------- CREATE A GlobeView FOR SUPPORTING DATA VISUALIZATION : ----------
    // Define camera initial position
    const placement = {
        coord: new itowns.Coordinates('EPSG:4326', 2.351323, 48.856712),
        range: 2500,
    }
    // `viewerDiv` will contain iTowns' rendering area (`<canvas>`)
    const viewerDiv = document.getElementById('viewerDiv');
    // Create a GlobeView
    const view = new itowns.GlobeView(viewerDiv, placement);
    // Setup loading screen and debug menu
    setupLoadingScreen(viewerDiv, view);
    const debugMenu = new GuiTools('menuDiv', view);

    // Store elevation layer ID for removal
    let elevationLayerId = null;
    // Track current opacity for cycling through values
    let currentOpacity = 1.0;

    // ---------- DISPLAY ORTHO-IMAGES : ----------
    // Add one imagery layer to the scene. This layer's properties are defined in a json file, but it could be
    // defined as a plain js object. See `Layer` documentation for more info.
    itowns.Fetcher.json('./layers/JSONLayers/Ortho.json').then(function _(config) {
        config.source = new itowns.WMTSSource(config.source);
        view.addLayer(
            new itowns.ColorLayer('Ortho', config),
        ).then(debugMenu.addLayerGUI.bind(debugMenu));
    });

    // ---------- DISPLAY A DIGITAL ELEVATION MODEL : ----------
    // Add two elevation layers, each with a different level of detail. Here again, each layer's properties are
    // defined in a json file.
    function addElevationLayerFromConfig(config) {
        config.source = new itowns.WMTSSource(config.source);
        const elevationLayer = new itowns.ElevationLayer(config.id, config);
        elevationLayerId = config.id; // Store the layer ID
        view.addLayer(elevationLayer).then(debugMenu.addLayerGUI.bind(debugMenu));
    }
    // itowns.Fetcher.json('./layers/JSONLayers/IGN_MNT_HIGHRES.json').then(addElevationLayerFromConfig);
    itowns.Fetcher.json('./layers/JSONLayers/WORLD_DTM.json').then(addElevationLayerFromConfig);

    // Function to remove elevation layer
    function removeElevationLayer() {
        if (elevationLayerId) {
            view.removeLayer(elevationLayerId, true);
            console.log(`Elevation layer ${elevationLayerId} removed`);
            // Disable the button after removal
            document.getElementById('removeElevationBtn').disabled = true;
            document.getElementById('removeElevationBtn').textContent = 'Elevation Layer Removed';
        } else {
            console.log('No elevation layer ID found');
        }
    }

    // Function to change tile layer opacity
    function changeTileLayerOpacity() {
        // Cycle through opacity values: 1.0 -> 0.7 -> 0.5 -> 0.3 -> 1.0
        const opacityValues = [1.0, 0.7, 0.5, 0.3];
        const currentIndex = opacityValues.indexOf(currentOpacity);
        const nextIndex = (currentIndex + 1) % opacityValues.length;
        currentOpacity = opacityValues[nextIndex];

        // Apply the opacity change
        const opacity = currentOpacity;
        view.tileLayer.opacity = opacity;




            view.notifyChange(view.camera3D);

        console.log(`Tile layer opacity changed to: ${opacity}`);
        document.getElementById('opacityBtn').textContent = `Opacity: ${Math.round(opacity * 100)}%`;
    }

    // ---------- ADD SOME WIDGETS : ----------
    // ADD A SCALE :
    const scale = new itowns_widgets.Scale(view, { position: 'bottom-right', translate: { x: -80 } });
    // ADD A MINIMAP :
    const minimap = new itowns_widgets.Minimap(
        view,
        new itowns.ColorLayer('minimap', {
            source: new itowns.VectorTilesSource({
                style: "https://data.geopf.fr/annexes/ressources/vectorTiles/styles/PLAN.IGN/standard.json",
                // We don't display mountains and plot related data to ease visualisation
                filter: (layer) => !layer['source-layer'].includes('oro_')
                    && !layer['source-layer'].includes('parcellaire'),
            }),
            addLabelLayer: { performance: true },
        }),
        { cursor: '+' },
    );
    // ADD NAVIGATION TOOLS :
    const navigation = new itowns_widgets.Navigation(view, {
        position: 'bottom-right',
        translate: { y: -40 },
    });
    // ADD A SEARCH BAR :
    // You can find more precise explanation on searchbar options in the doc
    // (http://www.itowns-project.org/itowns/docs/#api/Widgets/Searchbar) and in the searchbar example
    // (https://www.itowns-project.org/itowns/examples/#widgets_searchbar)
    // Define options for geocoding service that should be used by the searchbar.
    const geocodingOptions = {
        url: new URL(
            'https://data.geopf.fr/geocodage/completion?' +
            'text=&type=StreetAddress,PositionOfInterest',
        ),
        parser: (response) => {
            const map = new Map();
            response.results.forEach(location => {
                map.set(location.fulltext, new itowns.Coordinates('EPSG:4326', location.x, location.y));
            });
            return map;
        },
        onSelected: (coordinates) => {
            view.controls.lookAtCoordinate({ coord: coordinates, range: 20000, tilt: 45, heading: 0 });
        },
    }
    // Create the searchbar
    const searchbar = new itowns_widgets.Searchbar(view, geocodingOptions, {
        maxSuggestionNumber: 15,
        placeholder: 'Search a location in France',
        position: 'top-right',
    });

    // ---------- DISPLAY ATMOSPHERIC LIGHTING : ----------
    const atmosphere = view.getLayerById('atmosphere');
    atmosphere.setRealisticOn(!view.isDebugMode);

    // ---------- DEBUG TOOLS : ----------
    // Toggle atmospheric lighting on/off.
    const cRL = debugMenu.addGUI('RealisticLighting', !view.isDebugMode, function (v) {
        atmosphere.setRealisticOn(v);
        view.notifyChange(atmosphere);
    });
    debug.createTileDebugUI(debugMenu.gui, view);
</script>
</body>
</html>


```

### PR DESCRIPTION
**Pull request by Desplandis**
## Description
Fixes #2561. I however had to revert #2562 and reintroduce some minor render bugs (due to transparency) when hiding points by classification.

### CODE REVIEW

**Comment by AnthonyGlt** [comment]
Thanks :pray:

**Comment by gchoqueux** [comment]
revert part of #2374

**Comment by gchoqueux** [comment]
On master, the globe opacity seems to work on globe

https://github.com/user-attachments/assets/5d3564ab-9661-4185-ad09-77e917ad36e9

**Comment by gchoqueux** [comment]
Do you maybe think this wasn't the right way to fix this bug #2561 ?

**Comment by Desplandis** [comment]
I don't think it was the correct way to fix this bug. Unless we aim recompute the render order ourselves, but in both cases we should not hardcode the value of the render order.

**Comment by Desplandis** [comment]
As for the revert on the `depthWrite`, I agree with your previous issue on this topic.

**Comment by gchoqueux** [comment]
Hardcoded values are indeed not a good practice 
Layer transparency have several issues they should be listed and provide a robust solution.
What are the bugs on the master and what are the bugs with this PR @ftoromanoff @AnthonyGlt ?

**Comment by AnthonyGlt** [comment]
With this fix, we can't change the opacity/visibility of a pointcloud's class.
To reproduce it:



-     Edit the opacity or the visible attribute of a class in the DEFAULT ClassificationScheme of PointsMaterial.js . For example, opacity 0.0 in the "building" class
-     Load Sete point cloud from the 3dtiles_loader.html
-     Switch to classification view
-     Observe that the transparency isn't applied


It will be applied when the layer has an opacity < 1, but then the original bug is back : https://github.com/iTowns/itowns/issues/2540

[Screencast from 23-07-2025 09:30:43.webm](https://github.com/user-attachments/assets/bb20b1ee-e452-4443-8598-44d5ccf60b42)

**Comment by gchoqueux** [comment]
To renderer complex transparent meshes, a way is used [Weighted, Blended Order Independent Transparency ](https://stevinz.github.io/three-wboit/WeightedBlended.html)

**Comment by Desplandis** [comment]
Unfortunately I think this is local bug compared to what was introduced on the fixes. Unless we manage to fix the original issue (@ftoromanoff) in reasonable time, I propose that we revert the fixes.

**Comment by Neptilo** [comment]
Would it make sense to also add a non-regression test as part of the PR? This bug had been unnoticed for more than a year, so this would help noticing regressions earlier.
For example, the bug affected the opacity slider of the buildings in `source_stream_wfs_3d.html`, which had no effect. A test could be based on that example.

File: packages/Main/src/Layer/OGC3DTilesLayer.js [hunk 1]
```diff
@@ -146,6 +145,88 @@ export function enableMeshoptDecoder(MeshOptDecoder) {
     itownsGLTFLoader.setMeshoptDecoder(MeshOptDecoder);
 }
 
+// TODO: rename
+function referMaterialProperties(material, layer) {
```
Comment (jailln) [inline packages/Main/src/Layer/OGC3DTilesLayer.js:162]: Can you add a comment explaining why we do that please ?

File: packages/Main/src/Layer/OGC3DTilesLayer.js [hunk 2]
```diff
@@ -146,6 +145,88 @@ export function enableMeshoptDecoder(MeshOptDecoder) {
...
+    Object.defineProperty(material, 'opacity', {
+        get: () => layer.opacity,
+        set: () => {},
```
Comment (jailln) [inline packages/Main/src/Layer/OGC3DTilesLayer.js]: Why do you remove all the setters ? Why not redirecting the setter to the layer property instead ? :
```
  set: (value) => {
    layer.opacity = value;
  },
```

**Review by jailln — COMMENTED** [review]
Thanks for the fix ! I've tested it and it fixes the terrain opacity and brings back #2540 (which I reopened). I just have a few comments. Also, the coverage test doesn't pass.

File: packages/Main/src/Layer/OGC3DTilesLayer.js (hunk 1 above)
Comment (Desplandis) [reply packages/Main/src/Layer/OGC3DTilesLayer.js:162]: I kept the same mechanism to "override" the uniforms values by setting their getter to actually reference the layer properties (`ReferLayerProperties`). However I moved it in `OGC3DTilesLayer` because the condition for setting the `transparent` property is different for standard materials and our custom points material. We set the `transparent` property for standards materials when opacity < 1.0 and for points material when opacity < 1.0 **and** if some classification is non-opaque.

Comment (jailln) [reply packages/Main/src/Layer/OGC3DTilesLayer.js:162]: I understood all that, I meant could you add a comment **in the code** for future developers ?  

Sorry I was not specific enough. At least your comment is ready :grin:

File: packages/Main/src/Layer/OGC3DTilesLayer.js (hunk 2 above)
Comment (Desplandis) [reply packages/Main/src/Layer/OGC3DTilesLayer.js]: There is no case where we directly update the material properties (I mean outside the code of the layer) and I don't think we want that an edit to material property have a side-effect to the layer. I would prefer to have some kind of group of uniforms that we could share across materials (there is `UniformGroups` in three but I never used them yet).

File: packages/Main/src/Layer/OGC3DTilesLayer.js (hunk 1 above)
Comment (Desplandis) [reply packages/Main/src/Layer/OGC3DTilesLayer.js:162]: Yeah, at least the comment is ready x)

File: packages/Main/src/Layer/OGC3DTilesLayer.js (hunk 2 above)
Comment (jailln) [reply packages/Main/src/Layer/OGC3DTilesLayer.js]: Ok, I'm fine with your justification. Could we add a warning for external itowns user though please ?

File: packages/Main/src/Layer/OGC3DTilesLayer.js (hunk 1 above)
Comment (Desplandis) [reply packages/Main/src/Layer/OGC3DTilesLayer.js:162]: Done

File: packages/Main/src/Layer/OGC3DTilesLayer.js (hunk 2 above)
Comment (Desplandis) [reply packages/Main/src/Layer/OGC3DTilesLayer.js]: Done

**Comment by Desplandis** [comment]
@jailln I will add some tests to OGC3DTilesLayer to pass the coverage.

**Comment by Desplandis** [comment]
@jailln Ready for another review =)

**Review by jailln — APPROVED** [review]
Thanks for the tests :)
